// using ChessChallenge.API;
// using System;
// using System.Linq;
// using System.Numerics;
// using System.Collections.Generic;

// public class MyBot : IChessBot
// {
//     private double[][][] fc_weights;
//     private double[][] fc_biases, embedding;
//     private NeuralNetwork nn;
//     public Move Think(Board board, Timer timer)
//     {
//         if (nn == null)
//         {
// fc_weights = new double[4][][];
// fc_biases = new double[4][];
// int e0_cvcnb9cucsbDc0ckb5bIbSbScibCbJbXctbHbKaVb3aHaSaacHcGc4bvbHcWcscpcUdhc6cqc1dtcVcmcHdAdcc4cNedeaeabNb7cqcR;
// embedding = LoadParams(new string[] {nameof(e0_cvcnb9cucsbDc0ckb5bIbSbScibCbJbXctbHbKaVb3aHaSaacHcGc4bvbHcWcscpcUdhc6cqc1dtcVcmcHdAdcc4cNedeaeabNb7cqcR)}, 13, 4, 11, 34.281837463378906);
// int w1_b4cMcTcPcec3dmbYcdcWc4cGcbcfcVcgcacUdsctcacIdacCb0cbcycSb5b9cFcGcgcScccub8cEcccgcjc5djcOcccicObWcechcLctbDc7clczbKcKb2cFb3cGcwcRb0cxb3cbbZc2cEcfchcvckcjcgc8c8cMcfctcQcecfcbcyctchc1cjcpb6c4cDcJcacJcucbcfcdcVccczc9cQczcob1dnbSckcHcJb9cxcCcAczcxcncncEb4cVcMb7cLb1cScfb2bUczbIc0cTc6cbcVcHcscacRcbctcmcgbVdccucNcHc5bPcubPdeckcfchcBcvb9cmcIb7ckb1c0bUcacdcwbQb7cGdmbTcycxc4b0cHbRc2cpcDcqcKcecrckc9b6c1bJcBcKcucacQbHcpcpcWbYcechcScqcHbJcwbWcmbMcZckcKb_cFbVb4cNdccAcmcMcWcgb3b2czbJb_bPcxbycwcFc5cccncGcWcedkc0, w1_cPbRbHb8decDcDbWcjcyb5cHcKcDcYcrc2cVcTcycPcUclcicWcUcpctcycpcqcBcdcacIcFcvc9b3cLcTdccydmcWcudpc4cGcXc3c9cydfdidfcPcNc6cqcbcucOcCbZcKcsb8coc2bYcKc8dabPdlc0cXc3dncScEdbcgcMcIc6cJcRcDcGb_b6cpb4b8cscyb6bVcicCbOcfcMc8cvdscYcDc0ccc3cCdacgcRdacQbwcmb0cdbUcFcjcobPcxbXbQbZcbctcdclcEcubFb4c9cUcsb4cXcQcTbQb6cgcmbRctcTcabpcnbAbKcdcUcYcZbQcnb2bXcncRcBcRccdac9cjbGcOcscxcrbZdgcDcobWcvbOb8bJcKbCb9bPb3bLcrcCcEcWbXcpcOc8b2cQdnbOcecDc8bSdabzdnbPcQa8dhbMdjbXcvbGcHbTb5bSc3bNcIdscedpdlbEcTcWdcb2cBcLcIbvcAcycPbAcIcicR, w1_brcyb4cHbLbMbYcxbxcxb5cabucDcQcUb2cnbybYcqcJczcMcDcmbYcRctckcecUcvclcfcpcIcwb3cvcPcpb6cEcMcjcmcScsckcqcCcFcmbZdacob4b4dhcib2cbc3csb6b_cXcBcachc8cib5ckc7cib5c3cPcccccdcYclb9cEcWcob9cAc_cfb4cGcWcib_cvcUcBb1cycXcrb6cVcUckb5c1c0chbWcLcWclbZcAc5cdb9cxc6b5cccDc2b5cgcJcYcececDc1cecjcPc9ceb8cLc1ceb4cIcYcib2cwc_b1cicoc6b7ckcDc7b6cdcGc2b8cncAcYb5clcIc1b0cicFc_b6cjcCc6bWcccudebOccckdmbIcncnc9bUclchc9bZcgcvc8bRcncsc2bVctcrc1bXcscpc6bNcjcidmbHcpccdtbsckb7dobDclb5dibTcicadgbRcscndebLcxchdcbAcycqdhbycpcHcMcdcm, w1_cjc5bScuctcTb0cscHcYb6chcAcYb6cocGcSb1cBcCcVb4cwcRcRcfcwa1ctckcGcHcpctcUcodicScKbOcxczcGb1cMcvb7cjdfclcgb8cQcCcccjcScFc6cecKc4c_cpcqcGb5cBbucWbUb4cFcVbEckcScMbQcwdcdcbkccb9cHb9cna9cAcvcFbOcXcTcgcSb3bPchcac9bQb0cGcKbyceb3cNbNcpcHcSbAcycNcrbDcwcCcfcqcwbKcxcMcFcjc1chbOckcJb6cmb3b_bKcWcdclbYcRcIcEbUcMcCcpbScPb7cIcLcEbDcTcTcBbTcScib5bScmcncfb9cdcgcyclbYcrcGcFcmb9cNcocpcecObLcgcNcZbBdhc7cabPcOczb2b8b7cqcDcdbCcWcrcFbWctcucDb8cxcpcCcqcicZb2cicHc5bqcVdpcfbzb2dEbScbbUdxbXcbbHdoceb4bQdvb9cdb9c8ctcKcfcIcmbS, w1_cPbMbKbsdXcCbtczcIc0cbcMcuc8b0cqcddkbUa9b9dob_bAbSdacCcqcidsbQd1c0cIcKdXd3cTc6dfbLa5a4cCcpc_cMc0ccc_cMcZchc4cPc2cmc5cQc0cic6cOc0cjdbcKcYcbdacNcYcpc4cPc0csc3cNc3crc2cLc5crc4cPc3cuc3cLc3crc6cKc3cnc4cQc5cnc6cMcZcmc6cMcYcBc3cOc1czc0cLc3cCc0cKc4cCcYcNc6czc1cLc1cAcYcJc6cuc3cKc2cyc3cOc3cIc4cNc2cGc0cIc6cGcYcKc6cFc1cNc6cCc0cOc5cDcYcLc5cBc2cIc4cFc0cJc3cJc4cIc2cIc1cIc5cMc0cGc5cKc2cIc5cGc2cLc1cHc3cJc3cGc2cKc5cHc5cIcYcMc4cHc5cIc7cDc6cJc3cHc4cIc6cIc2cLc2cHc3cIc6cGc4cIc6cEc8cJc5cHc2cKc_cEcZcIc9cCc4cBc_cCc3cEc9, w1_cEc3cIc_cDc2cKdaczc4cHdbctc8cMc_czc4cBc9cFc2cBdjctc4cGdccxc3cFdcctc9cKdacyc9cLdbcxc7cKdicrc3cGdgcuc1cUclcmcocicjbRctcbcQcccxbMb8bQcxb0bObFcHb4bWbKcCb0bLbLczb0bEb9cLb2cabPcRb5cicmcdbVcob5ctbScob9cobSbUbUcFb1bDbRcHbXbJb0cqbXb0b8chbJbJcvcnbLcgckchbSb_b_crbTb3cgcrbPb_ckb5bUcob6cubUb3bXcrb6bqb1cxb2b6b7cdbSb9clb9bMb9cjcjb0cmb_cxbMcackcqbGcfcjcrbLb7cicsbVb_cfcjb1cgcrcibOcbcCb2bXbWczb_bTbVcBcbbZcdcncCbDb0cycsbLb5cvctbObXcpcpbVb1cbckb3bQcLbDb3b1cQbQbRb6cSbWbPb2cWb2bPbCcWccbIb5cLccbIbYcDckbWbUcAbVcab4debm, w1_cfb0c5bAb5cecXbIb5cmcVbUb0bSc4bRbSbBcXb5bObRcpcubIbJcKb1b4cGcGb8clcbcWb5b8bYcKccb0cAcqcAbScecDcfbRbTcOcmbUbPcjcAb7cnckcKcjalcfb6dOdjb3czcQcKcccIc2cqcpcscJcdbXcFcGcpb5cCcQcjb4cecMcibUb6cwcSbYcocvcPb3cVb_cKb1cwcycEb4dbcIclcbcRcMcLbRcucCb9b5c8cpcxchc0bHcRbPcGcwckczcCcmcgb1cydscmcjdicTchcucdc1b7cDcXcLcocqcYdabSb2cdcWcnb3cUcgcCcDcbc3bVcAb1cFbObPcvctcBbQcZcyczbHcmcMchcdc5b9cwb8caccbLcDdjc4c6c0cBczcncfcrcqb7ckbNddb4cTcRb7cCcnb8dybVcqcQcZb8cFbHdlcEbydbcRcyb5b_ddbAczcecXcnbUc4c8bWcQbYcxbWcebPchbNcKb3cick, w1_cmcbcCb2cLcqcubVcibYcWb7bNcQdjb6cyctcGcocjb3cKb7b5bIcqb_c6cydmchcRbUcscBdfcdcEcfbvcgdccnbKckc6cfcncdcMcab7bPcCbQcicrcJbYcvcicmbYcqcIc0cfcocUc1cdcwcccob2bUcLdicCcyc1c9cXctcZcUc4cxcHc6cQcvcRc_cOcqcRcZc1czcQddc4coczdhcYcodbcJcTcPdicIc3cGdocFcWcydgcKc4cEdhcsdfcGdicJdaczdmcDc0ckc6cOc4cvdicVcQcKdhcKc0cydecNcXcwdlcHcWcDdwcCc5cIdtcMc4cwdGcLc1cvdscPcWcEc8cOcGcGdhcPcScCdicOcRcIdncKcScJdrcCcYcQdocNcTcJdtcPcWcCdecNcNcGcWcZcBcIcXcTcQcGcWcYcQcKc0cUcTcMc7c0cUcTc9cPcUcPc8cMcTcPc2cTcTcIcNc8ctcJcPc1cOcIcPc0cQcMcC, w1_c3cRcMcPcZcPcTcLcYcScXcKcUcPcXcHcRcMcQcSc8cycVcKcYcCc0cFc7cJcHcCdacScEcFc4cRcYcJc0cOcScKcVcIcYcGcPcOcWcIdgcAcVcRc8cJcXc1dacvc0c1c7cxcQc4cYcOcPcKdbcLcTcIdacmc3cDdccxcVcTdBdlbOcKb0b6cTb8bJbBcAbZb0cecZchb4cScYcJb0cXc8cgb2ctcOcnbObOcwcacadgdvdgb1cPcMcrb_cWcPcmcdcHctcEcicHdgbWbZczcWcDcmdpcBcnbYc8cFcUccdlcRdeb6cScTcubQcxcAcnb2cIcVbYb8cMcKcpcvcmcubZb3cWcKczcscucCcwbVcOcjbWbKc0b2b0cpdic6cRbuc2czb6czcUcLcDbXb7cUbYcLdsdxcAcAcpcEb4ckctcpcoctb7c2bHb5b6cSbYcnbudacqcbcxcYcJctcrcBcncvbUc1cibKcKcObZcQcfcQcjcAcc, w1_cYczcFbVcVcncpbTcIcscub6czb1cOb4ddcgb1crdkbXcPbYcLb1czcgcvb8cLc4dkcMcccfc4bWbKcec2b4ckcqdebVcmb8crbKckb9c8bPcfbBcIcfcLb9cxcdb2cfcYb7bPcdcAb7cscJc4b3b1cqcNb4b7cwcPcgb4b4cEb6cIcrcObOcpcecIbEb9cmcab9cHbHcicScvbQb7cNcScddcdicvbTcNc3c0bTcUc9cNbDb1cQcibRchcEcObmcbcwcTb5c7cFcFcDc9ctb3cacGcIbWbGcGdecpbTcQdvc7b9cLcIcDcqc8b_crbscScAc_bTcGcHcnchcUcycmbYclcGb6bQcwd3c1bMc3c2b5cTcXcccYbLdHcMcacycLckcvbrcPcDbCcsbDdRbUcQcCcCb5cicLbUb3bPcmcPbYcQcectcxb5decscJcrcPcnbTcvczcobMbvcOcHb3cpcjdFcpb7cvbScobnddcPcrcqb9cm, w1_b1cacBcNbQdicZc1c2cTbvcDceb7cLc2bPbqcSc7cHcacJc7b0dnb5cPcbcKbsdubLdFbJc8cAdaclc5c9dccvdjcjc8bTc1cGcjcrcUb5chcCcJcschb5cIbVdcb0cAbUcZcdcxcAcDbZcHbHbTbUcmbvbtbTcOb7bGbYcQb2b_cwc_bIbub5cJcjbMcrcOcgbIcdcQceczcecFbEbYcGcHb5cgcjc0c4cQcicWc3cncictcHcdckcKcJcwclcHcTcvciclcKcxcecpcBcUcmcRcHc3cqcNcsccb9cRcNbYccb1c5b9cgcxcCchcrc4dncOcncfcLb5chcOcMcIckc8clcBcgcNcpcncscEczccb8cJc5b1ckcDcRcecactcQbOcfcUcAcqcocTcAcacjcCcucDcsclcRb4cqcEcKbTcqb6cAbVb_cccobHbQcZcCcvcicKcZbVcxcocuczcwcxdkbUcxcucZcBctb2cZbLcUcMc5cq, w1_cwdfcebWcub1cycwcnb8cKcbcwb7cLcgcncCcPbIcrbFc6b2cJcJdectcEb5dncub8cYcPcCceb4cDcyckcacRcqcQb0cFcicdccdecgcocHc8cDcybKcUb0ctcbcPbRcncbcYbUcqcacCcAcscfddcmcQcecUbScyb5c4crcecwc3cnb_czcOcccfbWcubOb2b1cVb3cacbcFbVb4bBcvbWcNcCcJcdcGcscGb1b3ctcmcCcMb4cKcPcwb8cmc2cab4cLc3b6b_cAc7b6b9chcXb4cfcWc_cqbYcec5cAb7cMcYcEb7cwcJbVbXcVcubSb7czcLb5cccSc3cgb8czc1cjbPcAcCcubTczcfcCbXcJcKcCb4cLcZbSb6cYc4cecgcNcBcob9cicJbScecDc3b9b8cJcScCbWcVcqcpcicJcAcwcgcHczcjchcCcHb4cbcocXb3cecEcUb1cmcycncwcccMcIcacecLcJcscccCc9bCck, w1_cEcZb6cicGc5bMcvcncDbZb8cxcBcjcocmcocBcaclcWbCcccpcBclbZcscJb0czb2c4b3clcbcVb8cGcvc2cqb5bXcMcgcgcicAb8cnbYcxb8cbcycOb9cLbTc3cdcAchc4clcrb1cQbJctcecPceb0bWctbWb1cCc8bIcLb0cRb2ddcdcNb7cPcbcQcab0cnc8bVcocncSb6b0cbcRb9b9cec4bQcdcgcEbZbTcdcHckcHcWcSbEchcEc3b3cccmcrcmcrb6c0dtctb7cjcQcBcgdddGcvbYcjcWb5cmcLddcmb7cGcXcSb2cIdgb1bWcDc4cob0c5cscjbPdacNdmcfcGdrcHcfcEcHcebYc0cWcIbbbSdfcxcndydebFaOc3c4cMb1cMcecgcqcSdkcObNc9cQdibzcKcscwcvctdocTcidfcqc_bWc1cycnbUcCcqcVbWcdcbblb3c2cJcicNcCbOcicsbWc4bNbDbWcRbObMcc, w1_cOcpbYbHdrbVbXc2cFbFbLcZdgbudacPdwbicqcccCbNcnchbRb0bxb3b2b0bhbzbxbDb2b6b7bOcncacZb_cpcic3cGb2crc6b2cMbWc3b1cTbSczbDczbFcDcpbvcLcvbxckcec6bXcvdndjbOdjbCcWbScCb8ducAc7bSdabUcbbSdnbbcyb4c5b5cCcrc8cpcNbPcjcqcdcdcPcAbKbPcVbscHcJc7cibJcjddb7bLczdxbnbAbRc0bKcAc2dzcedpdrdobMcKdadJcJb5cQcRb9b8clcAcOcuchcvcFcrceckcJclchctcGcfcmcqcDcycgclcKcqcdcicLcAcib7cIb8chcwcOcdckcQcxczcgcRcNcpcocIcSclclcxcHcecmcBcNcmb7cjcNcucecDcvckcjc8cQcvchcLcFcacfcycMcLcmcHcFcicjcoc0b2chcBcEcrchcycvceclcycBcycqcPcBcccicQcMcjclcBcK, w1_b8cocrcRb0clcVcEcfcpcycyb8cocIcscIcgcMcPcdcFcncBcucfcAcWb8cAcocEb4cCcvcrcmcAcEcBb5cjcwcKcucicAcEckcocecFbZcxchcybVcocrcEcwcvb7cMb4cwcrcIcDcxcicTb9chcecCb4crb2cTcfcpclcObVctcecUb8cOb0cFclcfb_cMbYcjctcIb_cpcncIckcRcfcQb8cRcccGb7cOcccIcdcicucVcicqczcWcecmcvcLb9cfb8cBb6clb7cEb0cqcEcZb7cpcBcRcecocncRbZb1cqckcackbKcvdbclbKcnc9b_bUcfc8cobIcscZcrbLcIdbcBbNcPc2czbUcwc2crbHcLc3cybPdecLcibWdocyczbNcMcOcobGcyc3cobib1drchbEdecEcvbXdacPcibBcTcIcUbKb4dibpbHclc0b2b8cBc3cicacKc4cbbcc7dpcfb1cWcDcgbMcAcOcmbzc7cxcB, w1_bRcZcVcvcscqcRcgb8cdcKcdbRb_cbbScudhcrcLbocHdmbtb9deb4cCcgcrcochcrb5cGbWckcOc0b6cfcEcAciclcecDctcucidnbIbQcCdhb6bLb8dlb8cAcwc4czb9bzchbIckcDc2crbYcbdfbJb9cscicacfcQc8cEclb1cOb7c1cbdcbycub6cLbVcubZcUbQcxbpcIbjbubScOcnb9cxdncjb8cbcIcdckcndeb0cnbIcpbAcFcmc2bWbVcGcTbVbNcodabsbOb5cKb3b3cAdnb2b6cSdqb_bPcGdrceczcucWbqcgcoc7bicOcqckclcndcbtbYcdcobTbVchcycEbWbUb7cCc9bSbAcKdKbKb4cZdGbJcjcVdjcacfc9dpcfcQbIcCcocyb_cMb_cJb5cLb8cScwcTbZcdc8cYbKcrdscVbJchdVcsbNcEedcCbDcDbBcBcmcKcqcObWcmcPcTbYb1cXdcbQcidec3bPcq, w1_dtc7bVcedFcPcwcRdlcLcIcMbGcyb8csb4cIbScIcwcTbPcMc_cUbIcscYc2b2cIc_cQb6cGc6cUcrc2cJcJcXcRb7cubVcDcccIbQcXcrcObVcDcNcLb2c2cVcOb4cTcTcmcBc9czcPcOdecCcHc6cxcdb8b4cQcgcEb6cLcNcabRcScPcsb0cRcLcicnc9cscrcPcYckcXc0c0b7cVdHc3cYbHbLcWcYbUbQcGcNb6cfcKcUbVctcTczcccLcScecBcPcFb6dccZcQbFdmdBcBchcdcuchcFb5ctb8cAcucfcWcucacIclcGcccOctcWb8cSbKc_cPcSbJcBdgdabYchbUaVd0chcWc4cRcrcUc7cWcncscXcacdcucUb0cic3dhc_cccKcFc3cjcGc3cMcibMctcycicecZcacdc4cocncucWcCcoclcQc9cPcycTcScBb4cdckcBcpc3dxcwcicfcMb8chdib9b2b6cVcsczcxcI, w1_cMctcnc7cNcvcpc6cAcdcgcGb0bCcucTcncDcAcYdccQcoczcmbHcGcvckckcocFcycecuc4cocQcKcVb7bObScKcZbPcJcDcIbZb0b_cvb8cnb4ctb1cIcncNcvcPb6cEcbcqdscjcfb5chc8bTcPcicDckcccHcHcacxchbXbRcocec9cpcJcccAcacCb5cWcEcYbBczcKcebHcRbRcgbQcLbMcKbsdnbOcmc1c_bRcRcoc2ctcUcecXcbcGbEcibkczcucGclbJcqc3cnc7bKcObycJccc1cjcLb3cTccckb6cUcgcqcvcOb8cbbOcHbIcfcrc7b5cBcNcXcccmbEctbrcxcccvbMcmcbcHbQb6cIctcfcdbJcfc0ckbTc2dQchbDb8cFcibPcRdicrb1cZdNbTbnbRcxcwbPcBcKdabDcuc5cXbycKcfbZbocNcuclb9dpcYc0bZcHcPcMbDcIc0cUb9dpcncPbPcXb5cYbQcMck, w1_crbTcCc9cbbXcsdabWcrc0cKcyckcUcJb0cmcPdbcZbYcQcQcva5c_cubWcBcYckb_cwckcDcvblcKc9bRbLb8c0b0ckcMcOcZcmcHcpcob3cQcdcubEccc3b_cpcsc6b_cDcgcmcibKcpcwbCb1cicGbBckcocNcgbQcgdubPcNcMcJclcQb9ducncub8cXcdcBcBdBchcPb0cucvb3b4cEb8cpcgb8bNcTbwc5b0ckbEcZb_cscac5bBbZb_cAcnb3bZcRbBcKbwczb6ctbRcMcgcscRdgcRcmbScPcbcebYc3bIc7bKcQcjcxb4cEb7bUcJdocrcfcJdlcocncucRckb0cUdkcEclcDdnbBbzb4cWb3cYcScPbIcAcPdnbGcGb2cOb1bNcdc6dDb4cAdldIb2b_cGdbbWb9cQcOcdcbcKcJcLbZcZcPcMcebZbVczb2bpb6bXbVcedLbjbKbKdlcEbvbKdxcrcocCcAb3b8crcbb7, w1_b9dcchcpcRdpbdcBbodyaacqbrbXdMcMbHcLcFbSb7cFccb6bJcxctcxb2chclchbXbHdpcmchc_chckcpdzbtc0bZcYcAcccccAbTddcucxcUcwcqcmcicCcrcncxc_bwcCcAb8cJcqcvcWdvc5bKb5bLc1cRb6chcBcxcjcfbZcAcscCcvbTcwcRb1b2bLbbcodAb9cobXc2bRducLcMcSb3cPdAb9cectczbDcucxckchbYcHcTbIcgcBdbcrbxbWc9bZbQcedCbLd8bRcgcjb1cBdmcnchcMc_b9cGbYdabUcccOcPcgcgctdecccpcnc7cEbTcbcZaOdGcqcEcjcccZdBcEcYcDc9cccjcAc4ctcgchdfclcQcTdebVbVcMdqcocGcLc_b2cUchcRb7cYclcIbSbabVcUc_cQb1c_dacSbVcAcXb_cfcDcVcsb1cXdecMb4cvcTcQcdcOc7cNb8cIdrcdbKc1b3cKb3cUcvcubu, w1_b6cHckb7bZcCcBbVcuc3ceb0c4cxb8bYbZcNcTbMcZcecFb5drdmdbctcZcAcqbFcRcacucicScOcob7cTcpcwbvcacXcDbSdIc5c1cecFcTb5cncRcEcRcxcjcsb9b_cYc8b_bZbOcycfbHcXb7cobRdpcOcCb9cTcNcrclcwcCb1b7c0c3cFbKb_cObDcQb8dDcbb2cTcocxbVb4bNcAdfcKc8cnb4cecEbOcycscgcLc0c6dyclcfbQc1bLcubFcTclcHbTdbcnccbldkcbcycdcHbYczcIdecWdNbVcUchcOb6cNcccPbUcsbScjcnc0cscjbRdrb0cEbQcRbYdfbVcxb9c0bscncNcecLc3bubJbVc6cjbZcmc_b1bVchdbbJbMb6cZb1bRb8c5bXckbScrbictcucRcucMcEcUbCcqbtcaccczcucWcyc_cgc8cAcZchcWcxc4cpcMcyc5ckcNcAc1ccc4cAc_cnc4cCcZcDc8, w1_cIcWb0cZcAcYb2c7cwc5bXc3cAcYbYdncrcQcfc4cvcWcac4cscYcbcYcrcZckcTcDcQb9cTcDcZb4cXczc1b1c3cAc5bUc3cDc0cacYcAc5cicVczc0cmcUcDcXcjcQcGcPcacIcwc5ckcMcEc5chcQcCc5cmcPcDc_cscMcQc8cwcScEc2cncRcOcWcocOcHcUcmcLcvc4clcHcJc0ctcOcFc1cucEcKc9cycKcJdbcAcJcQddcscIcPcZctcNcEcZcocKcnc4czcJcBc1cycKcDc3clcHcNc6czcLcFc_cDcGcNdccAcHcFc7czcFcIc4crcScddacucScec2cgcZckcWcwcYcpc5cqcTckdacDcWcnc2cxcPchdbcvcUcic_cMc8cbdecAc0chc_cFcVciddcFcXchc_cxc5cfdbcGc1cldicKcZcdddcLcWcidcb4cAcVbEcZbZb8cRb5b8cHc5b8b5cqc9crb4clcScpcdcEcS, w1_bYb9cCdib1bNcbcIcob0b4cJb_b8dscicibXcqcKb5cjcAc5b5cecJc8ctcgc4cJczb6cXcCcrb9cLcpcwbScOcacDb2cvcPbWchcQcnb9b3cXc8cpb2cncUcwcecPcPcmcqcNc_cqcfcPcPb4cecIddcicdcVcxcjb8cvcHcfb_djc8c1b2cMcTbSbXdacGcrctc9cTctcNcoc7b6b5cqcDcrckb_dgbNcgcqdjbPcbb3c7bSbCcKcbcfclczc8bVcDchcPbZbPc0cSbHcobUc0clctb7cBb9cbcldhb5b1cjcvbscvbUcBcccsb8cIb9b7cecGbXcHcgc4cfcmcmcKcscJb3cEbUcEb1cGbYbYcscOb3cncdcwb3b1coc7bZcRcccXb3cIcmcJchc2cfcPbObZcfc7bDbCb8c3b9bwbZcGbIcccwddb7bNbNczbBbLcac9bScCc2cZbHcDc2c7b2bTceb_cXczbWcYdbc0bOcjcScs, w1_bTcbc5bWcccMc3clbYcHc7cnbZcSc8czb7cacScpbRbNcHctbZcIc0cacndKcycEb3crcWb6bPcqc1b_bRbUdkbKcqcYcdbPb5dvcNcVcac0ctc5bIddcSbTbTcoc2cjb6cRdacsb1cacPbZcfdrcUcXcBcAcccycfcYcccVbNb7cVcucsczcRccb4cvcIcbcAcKdtcScmcKcRb7bZcCcPcjcncub6ccbyctcJbRbCcuc7cmcbcvczclcaczcmbEc6bPcHcncpcxczcBcHcYcEcYcUcSctcicicscAb6cxcJcDcfb6cVc7cdcHcpcJcpcrcrc4cucabXcEcccIb4cCb3bXclcqcgcEcicZcacubQcVcdcMclcScocPbQcTb3ckcoc7cwbRb4dpcxbNbTclbPc0cacWb3cLcFc5bucDcmcRckb1cuc1b7bXbXczbBbOcpc1cpbTb4cwbGcdcMdhb1b7ctcYcicjbHclbkcqdhdmchb1cm, w1_cjchcKcmdbc2dib4cLcBcXcdc4c9cZcncNcUctcDcCcwc4cgcAcSc_clcRcYdicuczcGczbMcVc7b8czcycHcDcscJb9cJcycNcOcxb4cdcyc8cAcjcucxcjcNbYcRcAcYbTbQbKdqcQcbcUcXcrclcybXcvckcAbEcucpchcfcicHc0c1cwcPcwc_cgctcMddcfcFbYdCcBb6cscpb9cnbWcecfcRbLb2cGbPb_cicMcab2b2dbbQcQc1cFb5czcUcwb4bLdccAcdcocEcicAclcrcdbPbYcyckclb_cob_bMclccdmbMcfbXdebKcDdvcEbxcQcmcFcPctcecLb9dcbZcLcucZb6cXcMcxbzcZcbdbbTcZbNdHbvdbctckb1dpbQdhclc1bvcAbNcUcrcIb1cEb_cubVcRcdcYbUcwbSdXbHcFczdna_dmcmdqb7cyb_cCcicxb3cncfcMcfcuckcyb9b4cqc9cObTb6cEcmbRbQcq, w1_cCb4cscIcEcBcGcqcFcwcecib0b3cjcqcVchcfb6cIcrckcAcOcbcmcNc_cychcLcYdpcjc0cXcYcfcvc0cycgcScZcHb8cTcJb9ckcIcQcichcccMb6cdcJcEcMcecDcHcAbQcCcnckcpcucJcTb4cycucucec7c1cHcec4cybAcgcycKcdcrcIcPcDcacmcDcmb9cycFcgcocKcJcccacMbYcocucNcmcrb7cwcjbLcdc8cRb6cdctcycwcgcicMb4b3b_cjclcdcGcwcacEcFc5cDcaclcCcicqcIc0cicCcbcEcLcsclcVcecDb0cKcjcGciciclcmctcBcicscrcEcdcDb4cJcvcsb0c2cjcncldccRckcxcJckcpcXcOcCcncpczcpcyckcMclcGcmchb8cBcicJchb8cucXcvbNcfb6bPcjb1ctbycpcwc6cEcPb_cLctclcocpchcOb9cyb8cdbVcubDcdcwcDb5cgchczb9, w1_b7bWczbPcccfcDcub9bwclbDcXcVcRchcbcncOcacncccbcvcLbAcbcRckbIcAcVcwb7cDcQcDbPcmcKckb6cPdAcFbNcCcAcDbnb6cwcbbUclcTcobScQcwcgccdvcKb7b6cDc6cAbZcKc7cab3cAcTckbKcJczcEcmdob_cybNcxcccYb3cXcNcbbUcRcpcjcdcJclcDcUcZdVcgbWc0cEcdbsb9cQcpclcUcscfbLdacAcGcucKcFb4bCcMcVbrcTcbcPccbYb9cNcecvcHcBcscgcOb9cvcAcedfcyclcJctcsb6cMdqbAcqcoc3bWcNb6cIcKbGcOc2b3cwcqcfbUchb1cSbQcJcmcUcwb_cVdicoc_bWc6cfc5cUcScucmcJcTbxcOcCcNcScmcudncCclcBcNbRcQbNcGcvchb7c5b0cZb8c8b6b9crdjb3bVcjdgcwcxcpcPbOctcnc6ckb3b3cWcab9bKccbfc0bEcrbVbw, w1_b4cWbZbZb8cWbObVcjcYcmbLbRcEbwbRb0cHbtb0cdcLbQcvb2cCbqbObJcXbhbXb7cccncfb0cqdockbUcjcpcEb6cGdfclb8b9cYcfb1cecOclcfcHdfcIbTcgcXcsbYcncYb7b5cPcWbXbWc8clccb3cwcScnb7cncEclb4cCcUceb_cMczcmb2cUcFcrb3cCcGcmb5cYcPb1b1cPcyceb5cDctb6b_c1cNcEcecvcIb7b1cUcZcacdcEcycib2cNcNcocdcFcGb1cucyc2b5cecFdbbWb6dacIbYcac1cObUcscpcJb1bZc4cRb6bVcYcXcwcdcdc8bAb2cMcMb4cycOcGcFcdcjcDbHcgckcycpb8cCcVbHcycMcEb3cxcscEcfcdchdbb1csbSdhbHcOcgc4chcPb8cRcaclchc2cdcjcpcJcscAccc4bZcIb_cSbRcOb9dsblcCb3cDcncBcdc9bTb0cwcUb1cjb_cIbEcAbY, w1_dfcaccbIckbPcQcuc1b2bScbczbNcichcSbHcucrcVbSb2chcJbYbYcDc1b5b5chcZbRcwcxcTbHb8cfc2bLcTcncnctcpcGb3b3cecUb1b4cccXbXbWcecXb1bYcacVbZbYcbcWb4bVcec0b4b3cccJcfb3ccc3bKb8ckcYbMb_coc3bJcacicSbQb4cec1bIb7cfcVbKcccicWbNb8cccUbRb9cccMbTb9cdcKbPb9cdcNbPb8cdcLbJcecicIbNcacdcJbOb8cdcMbPb8cfcGbTcacfcFbWb_cdcFbTb9cdcEbQb8cbcEbTb9cbcAbQchcbczbTcbcccAbWcbb9cDbUb_cfcFbYcbb9czbRcib9cEbWcab8cCbXb9b_cwbZcib8cBbZcfb8cAbSciccczb0ceb7cAbQclb8cAbPcmb9cubPclb6cqbRcpb7cAbRcmb8cwbVcmcccybScjcecwbTcocbcCbPczb4cDbKcub8chbRcv, w1_bYcubSctb3cubRcpb_cEbVcob9cBbXb_ckcwbTclcccrbYcmb8cFbPctcbczbVclb8cvbUcgcccwbScrcbcvb0cncbcJbUcncccnbZcncbdccGcGb_cbcBcTcPccbKc5cucnbwcEcYctbNcWddcfbQcNc_cjbUcGc4cmbNcEcrclcwbXb5b9b2cNc3chbLc5cHcmcicUcKcjcbcLcZchbYc7cNchctcWcEcgcPcRcFcDcdccdecXcycFcJcIcmc8czcecuc0cJcjcIcVcXb6czc5cCb3cqcZcNb9chc2cwcectcDc1b2cScEcvcAcBcPcvcucOc6cCcccKc5cNb8cNc_cCb3cUcWcUb1cMcScBb6cAcxc_b4cMcucvcZcUcRcuctcAcJcycucHcMcHcrc_cVcscncLcQcHcacLcFcXb2cjb6c6coc5cQcmcOcXcSckcXc6cScdcXcLcIcAcxcGcLcHcrcXczcycNcbcScYcob2csdecq, w1_c7cKcvcWdncLcrcZdhcMclcUc4cLclcZcHcLclcKcvcMctcOcrcPdfbRbTbGdxcScvcNcHcJbZdmbZc9cec8chcOcscVcocXb2dmb0c4b5dbcmcEbzcbcMcZbFbQcwdpbRcacqcxbZcpcycKcrcqcncGckcncpcAcfcmcHcDcmcqczcMcgcqcAcBckcjclcDcGcpcscKcycpcucOb6cncycxctcqcScOb_clcLcGcmcpcDczcwcgcvcrb1cicLcmcuclcHcecvclcycBbTcrcScIceckclcxcwcmczcGcfcncDcCcpclcGcEb_cocHcrcccmcxcycpcmcVcDb2cuczcDb3cmcDcEcecpcFcBb_cqcrcJb_cpcscDcecpcGcwb7ckcNcCcucyckcvcqcqb9cCb_cncrcBb9ctcJczctcxcecMb_cqcmcHclcpcvcGb_ctcwcwcfcocacKcacpb_cCb7ctcycIcgcpcocFcfcvb_cFcacm, w1_cjczckcIbYcOcacub6cGcicmcpcMcccvcicLb9cockcEcococtcFcgctb9cIcgcFb9cTb7crcicAb1cJcfcycecjcjcQb7cqcocMcdcpcocHb_cmb6cAbWclcpcFclclcicLcdckcpcEcdcpcqcEb1cscrcuckcncscGcBcLcEcocWcNcmcAcHcBc9cVb_cwdhcOb2cpdxc1bYcedpczcDbVcAcJcNbJc5cKcoc9cocBclddcJcub5cSc2cMbFcDc9dabDczcwcPcbchcuc2cvbIbYc_cnbCcfc4cvcXcacCcCcLcYcAb6cPcKczb6cNc3cGcfcsdlcMbXcdctcYcfbKcocZcnbkckdbcxcLcnc9cIcqcbcEcscAcdckcucTcbckbXcLcrcnb2czcdcCb4b5crcLbZbDcydmcMb8cadlcqcDbZcOcNcKb5cncAcqbXbYcHcHcsb4cjcfctcecccab6cob3bTckdtcvcdchdncBcbb9cK, w1_cOcycgcfc4cycocddab2ctbVcZbUcVb0cwbFcrb_b8bQcqdGcEb4b7dfcGcecwcYcRchbWc2cIchcobWdxb1cGbFdqcgdqa8drcocIa5c2cddrdhc4b2d_c7cNcAdWcUcwc6cFcNdgbZbPcAdmbVb2b2dtcscibXcFb8ccbXcKbEcTa8cYctbbbUcQc9ckbHcjc3chbScVdBb3bHcYc0cyb4cBdfbMbTcbc9cabQcNc6cLbJb8cWcMbQcDcIcjbLc5cbcfbKcqdjcEbQcAdecebIcncVcfbXcLcXcNbKcuckcMchdWc0cTbLcMc6bKcdcldaceb8cscochbSb9dkcychcQclbZbOcRc6cvbNcMclcrbLdcchb1cBcXcTcBb6cqcKcdcrcedjctbkcGcOcebTcIb4cqcQcKb7b1cUdec5cobIc_ctclcVcycGb5cGcicHcEcwbOcxb1bScfcGcbcHcwbWcmcocYdAczb_bZcNb6b2c2dj, w1_cicncWdCckbXb9cWbBccbVcGb3cGbBcFbKcRbHc9cgcIb1cVb3cicAdlcidfcjc1cdcyb7drb1bIb6cDbtclbZcUbUbJbPcNb6b8bFcNb3cYb_cBcidcbJc1bVc3cbcVcgbEbXcYbKbYcLc7cgbNcdc_cqb4cpc9cmbXcLdfcwblbYcPcgc7dgdmcpb5bVcSbJb0cecvclcv;
// fc_weights[0] = LoadParams(new string[] {nameof(w1_b4cMcTcPcec3dmbYcdcWc4cGcbcfcVcgcacUdsctcacIdacCb0cbcycSb5b9cFcGcgcScccub8cEcccgcjc5djcOcccicObWcechcLctbDc7clczbKcKb2cFb3cGcwcRb0cxb3cbbZc2cEcfchcvckcjcgc8c8cMcfctcQcecfcbcyctchc1cjcpb6c4cDcJcacJcucbcfcdcVccczc9cQczcob1dnbSckcHcJb9cxcCcAczcxcncncEb4cVcMb7cLb1cScfb2bUczbIc0cTc6cbcVcHcscacRcbctcmcgbVdccucNcHc5bPcubPdeckcfchcBcvb9cmcIb7ckb1c0bUcacdcwbQb7cGdmbTcycxc4b0cHbRc2cpcDcqcKcecrckc9b6c1bJcBcKcucacQbHcpcpcWbYcechcScqcHbJcwbWcmbMcZckcKb_cFbVb4cNdccAcmcMcWcgb3b2czbJb_bPcxbycwcFc5cccncGcWcedkc0), nameof(w1_cPbRbHb8decDcDbWcjcyb5cHcKcDcYcrc2cVcTcycPcUclcicWcUcpctcycpcqcBcdcacIcFcvc9b3cLcTdccydmcWcudpc4cGcXc3c9cydfdidfcPcNc6cqcbcucOcCbZcKcsb8coc2bYcKc8dabPdlc0cXc3dncScEdbcgcMcIc6cJcRcDcGb_b6cpb4b8cscyb6bVcicCbOcfcMc8cvdscYcDc0ccc3cCdacgcRdacQbwcmb0cdbUcFcjcobPcxbXbQbZcbctcdclcEcubFb4c9cUcsb4cXcQcTbQb6cgcmbRctcTcabpcnbAbKcdcUcYcZbQcnb2bXcncRcBcRccdac9cjbGcOcscxcrbZdgcDcobWcvbOb8bJcKbCb9bPb3bLcrcCcEcWbXcpcOc8b2cQdnbOcecDc8bSdabzdnbPcQa8dhbMdjbXcvbGcHbTb5bSc3bNcIdscedpdlbEcTcWdcb2cBcLcIbvcAcycPbAcIcicR), nameof(w1_brcyb4cHbLbMbYcxbxcxb5cabucDcQcUb2cnbybYcqcJczcMcDcmbYcRctckcecUcvclcfcpcIcwb3cvcPcpb6cEcMcjcmcScsckcqcCcFcmbZdacob4b4dhcib2cbc3csb6b_cXcBcachc8cib5ckc7cib5c3cPcccccdcYclb9cEcWcob9cAc_cfb4cGcWcib_cvcUcBb1cycXcrb6cVcUckb5c1c0chbWcLcWclbZcAc5cdb9cxc6b5cccDc2b5cgcJcYcececDc1cecjcPc9ceb8cLc1ceb4cIcYcib2cwc_b1cicoc6b7ckcDc7b6cdcGc2b8cncAcYb5clcIc1b0cicFc_b6cjcCc6bWcccudebOccckdmbIcncnc9bUclchc9bZcgcvc8bRcncsc2bVctcrc1bXcscpc6bNcjcidmbHcpccdtbsckb7dobDclb5dibTcicadgbRcscndebLcxchdcbAcycqdhbycpcHcMcdcm), nameof(w1_cjc5bScuctcTb0cscHcYb6chcAcYb6cocGcSb1cBcCcVb4cwcRcRcfcwa1ctckcGcHcpctcUcodicScKbOcxczcGb1cMcvb7cjdfclcgb8cQcCcccjcScFc6cecKc4c_cpcqcGb5cBbucWbUb4cFcVbEckcScMbQcwdcdcbkccb9cHb9cna9cAcvcFbOcXcTcgcSb3bPchcac9bQb0cGcKbyceb3cNbNcpcHcSbAcycNcrbDcwcCcfcqcwbKcxcMcFcjc1chbOckcJb6cmb3b_bKcWcdclbYcRcIcEbUcMcCcpbScPb7cIcLcEbDcTcTcBbTcScib5bScmcncfb9cdcgcyclbYcrcGcFcmb9cNcocpcecObLcgcNcZbBdhc7cabPcOczb2b8b7cqcDcdbCcWcrcFbWctcucDb8cxcpcCcqcicZb2cicHc5bqcVdpcfbzb2dEbScbbUdxbXcbbHdoceb4bQdvb9cdb9c8ctcKcfcIcmbS), nameof(w1_cPbMbKbsdXcCbtczcIc0cbcMcuc8b0cqcddkbUa9b9dob_bAbSdacCcqcidsbQd1c0cIcKdXd3cTc6dfbLa5a4cCcpc_cMc0ccc_cMcZchc4cPc2cmc5cQc0cic6cOc0cjdbcKcYcbdacNcYcpc4cPc0csc3cNc3crc2cLc5crc4cPc3cuc3cLc3crc6cKc3cnc4cQc5cnc6cMcZcmc6cMcYcBc3cOc1czc0cLc3cCc0cKc4cCcYcNc6czc1cLc1cAcYcJc6cuc3cKc2cyc3cOc3cIc4cNc2cGc0cIc6cGcYcKc6cFc1cNc6cCc0cOc5cDcYcLc5cBc2cIc4cFc0cJc3cJc4cIc2cIc1cIc5cMc0cGc5cKc2cIc5cGc2cLc1cHc3cJc3cGc2cKc5cHc5cIcYcMc4cHc5cIc7cDc6cJc3cHc4cIc6cIc2cLc2cHc3cIc6cGc4cIc6cEc8cJc5cHc2cKc_cEcZcIc9cCc4cBc_cCc3cEc9), nameof(w1_cEc3cIc_cDc2cKdaczc4cHdbctc8cMc_czc4cBc9cFc2cBdjctc4cGdccxc3cFdcctc9cKdacyc9cLdbcxc7cKdicrc3cGdgcuc1cUclcmcocicjbRctcbcQcccxbMb8bQcxb0bObFcHb4bWbKcCb0bLbLczb0bEb9cLb2cabPcRb5cicmcdbVcob5ctbScob9cobSbUbUcFb1bDbRcHbXbJb0cqbXb0b8chbJbJcvcnbLcgckchbSb_b_crbTb3cgcrbPb_ckb5bUcob6cubUb3bXcrb6bqb1cxb2b6b7cdbSb9clb9bMb9cjcjb0cmb_cxbMcackcqbGcfcjcrbLb7cicsbVb_cfcjb1cgcrcibOcbcCb2bXbWczb_bTbVcBcbbZcdcncCbDb0cycsbLb5cvctbObXcpcpbVb1cbckb3bQcLbDb3b1cQbQbRb6cSbWbPb2cWb2bPbCcWccbIb5cLccbIbYcDckbWbUcAbVcab4debm), nameof(w1_cfb0c5bAb5cecXbIb5cmcVbUb0bSc4bRbSbBcXb5bObRcpcubIbJcKb1b4cGcGb8clcbcWb5b8bYcKccb0cAcqcAbScecDcfbRbTcOcmbUbPcjcAb7cnckcKcjalcfb6dOdjb3czcQcKcccIc2cqcpcscJcdbXcFcGcpb5cCcQcjb4cecMcibUb6cwcSbYcocvcPb3cVb_cKb1cwcycEb4dbcIclcbcRcMcLbRcucCb9b5c8cpcxchc0bHcRbPcGcwckczcCcmcgb1cydscmcjdicTchcucdc1b7cDcXcLcocqcYdabSb2cdcWcnb3cUcgcCcDcbc3bVcAb1cFbObPcvctcBbQcZcyczbHcmcMchcdc5b9cwb8caccbLcDdjc4c6c0cBczcncfcrcqb7ckbNddb4cTcRb7cCcnb8dybVcqcQcZb8cFbHdlcEbydbcRcyb5b_ddbAczcecXcnbUc4c8bWcQbYcxbWcebPchbNcKb3cick), nameof(w1_cmcbcCb2cLcqcubVcibYcWb7bNcQdjb6cyctcGcocjb3cKb7b5bIcqb_c6cydmchcRbUcscBdfcdcEcfbvcgdccnbKckc6cfcncdcMcab7bPcCbQcicrcJbYcvcicmbYcqcIc0cfcocUc1cdcwcccob2bUcLdicCcyc1c9cXctcZcUc4cxcHc6cQcvcRc_cOcqcRcZc1czcQddc4coczdhcYcodbcJcTcPdicIc3cGdocFcWcydgcKc4cEdhcsdfcGdicJdaczdmcDc0ckc6cOc4cvdicVcQcKdhcKc0cydecNcXcwdlcHcWcDdwcCc5cIdtcMc4cwdGcLc1cvdscPcWcEc8cOcGcGdhcPcScCdicOcRcIdncKcScJdrcCcYcQdocNcTcJdtcPcWcCdecNcNcGcWcZcBcIcXcTcQcGcWcYcQcKc0cUcTcMc7c0cUcTc9cPcUcPc8cMcTcPc2cTcTcIcNc8ctcJcPc1cOcIcPc0cQcMcC), nameof(w1_c3cRcMcPcZcPcTcLcYcScXcKcUcPcXcHcRcMcQcSc8cycVcKcYcCc0cFc7cJcHcCdacScEcFc4cRcYcJc0cOcScKcVcIcYcGcPcOcWcIdgcAcVcRc8cJcXc1dacvc0c1c7cxcQc4cYcOcPcKdbcLcTcIdacmc3cDdccxcVcTdBdlbOcKb0b6cTb8bJbBcAbZb0cecZchb4cScYcJb0cXc8cgb2ctcOcnbObOcwcacadgdvdgb1cPcMcrb_cWcPcmcdcHctcEcicHdgbWbZczcWcDcmdpcBcnbYc8cFcUccdlcRdeb6cScTcubQcxcAcnb2cIcVbYb8cMcKcpcvcmcubZb3cWcKczcscucCcwbVcOcjbWbKc0b2b0cpdic6cRbuc2czb6czcUcLcDbXb7cUbYcLdsdxcAcAcpcEb4ckctcpcoctb7c2bHb5b6cSbYcnbudacqcbcxcYcJctcrcBcncvbUc1cibKcKcObZcQcfcQcjcAcc), nameof(w1_cYczcFbVcVcncpbTcIcscub6czb1cOb4ddcgb1crdkbXcPbYcLb1czcgcvb8cLc4dkcMcccfc4bWbKcec2b4ckcqdebVcmb8crbKckb9c8bPcfbBcIcfcLb9cxcdb2cfcYb7bPcdcAb7cscJc4b3b1cqcNb4b7cwcPcgb4b4cEb6cIcrcObOcpcecIbEb9cmcab9cHbHcicScvbQb7cNcScddcdicvbTcNc3c0bTcUc9cNbDb1cQcibRchcEcObmcbcwcTb5c7cFcFcDc9ctb3cacGcIbWbGcGdecpbTcQdvc7b9cLcIcDcqc8b_crbscScAc_bTcGcHcnchcUcycmbYclcGb6bQcwd3c1bMc3c2b5cTcXcccYbLdHcMcacycLckcvbrcPcDbCcsbDdRbUcQcCcCb5cicLbUb3bPcmcPbYcQcectcxb5decscJcrcPcnbTcvczcobMbvcOcHb3cpcjdFcpb7cvbScobnddcPcrcqb9cm), nameof(w1_b1cacBcNbQdicZc1c2cTbvcDceb7cLc2bPbqcSc7cHcacJc7b0dnb5cPcbcKbsdubLdFbJc8cAdaclc5c9dccvdjcjc8bTc1cGcjcrcUb5chcCcJcschb5cIbVdcb0cAbUcZcdcxcAcDbZcHbHbTbUcmbvbtbTcOb7bGbYcQb2b_cwc_bIbub5cJcjbMcrcOcgbIcdcQceczcecFbEbYcGcHb5cgcjc0c4cQcicWc3cncictcHcdckcKcJcwclcHcTcvciclcKcxcecpcBcUcmcRcHc3cqcNcsccb9cRcNbYccb1c5b9cgcxcCchcrc4dncOcncfcLb5chcOcMcIckc8clcBcgcNcpcncscEczccb8cJc5b1ckcDcRcecactcQbOcfcUcAcqcocTcAcacjcCcucDcsclcRb4cqcEcKbTcqb6cAbVb_cccobHbQcZcCcvcicKcZbVcxcocuczcwcxdkbUcxcucZcBctb2cZbLcUcMc5cq), nameof(w1_cwdfcebWcub1cycwcnb8cKcbcwb7cLcgcncCcPbIcrbFc6b2cJcJdectcEb5dncub8cYcPcCceb4cDcyckcacRcqcQb0cFcicdccdecgcocHc8cDcybKcUb0ctcbcPbRcncbcYbUcqcacCcAcscfddcmcQcecUbScyb5c4crcecwc3cnb_czcOcccfbWcubOb2b1cVb3cacbcFbVb4bBcvbWcNcCcJcdcGcscGb1b3ctcmcCcMb4cKcPcwb8cmc2cab4cLc3b6b_cAc7b6b9chcXb4cfcWc_cqbYcec5cAb7cMcYcEb7cwcJbVbXcVcubSb7czcLb5cccSc3cgb8czc1cjbPcAcCcubTczcfcCbXcJcKcCb4cLcZbSb6cYc4cecgcNcBcob9cicJbScecDc3b9b8cJcScCbWcVcqcpcicJcAcwcgcHczcjchcCcHb4cbcocXb3cecEcUb1cmcycncwcccMcIcacecLcJcscccCc9bCck), nameof(w1_cEcZb6cicGc5bMcvcncDbZb8cxcBcjcocmcocBcaclcWbCcccpcBclbZcscJb0czb2c4b3clcbcVb8cGcvc2cqb5bXcMcgcgcicAb8cnbYcxb8cbcycOb9cLbTc3cdcAchc4clcrb1cQbJctcecPceb0bWctbWb1cCc8bIcLb0cRb2ddcdcNb7cPcbcQcab0cnc8bVcocncSb6b0cbcRb9b9cec4bQcdcgcEbZbTcdcHckcHcWcSbEchcEc3b3cccmcrcmcrb6c0dtctb7cjcQcBcgdddGcvbYcjcWb5cmcLddcmb7cGcXcSb2cIdgb1bWcDc4cob0c5cscjbPdacNdmcfcGdrcHcfcEcHcebYc0cWcIbbbSdfcxcndydebFaOc3c4cMb1cMcecgcqcSdkcObNc9cQdibzcKcscwcvctdocTcidfcqc_bWc1cycnbUcCcqcVbWcdcbblb3c2cJcicNcCbOcicsbWc4bNbDbWcRbObMcc), nameof(w1_cOcpbYbHdrbVbXc2cFbFbLcZdgbudacPdwbicqcccCbNcnchbRb0bxb3b2b0bhbzbxbDb2b6b7bOcncacZb_cpcic3cGb2crc6b2cMbWc3b1cTbSczbDczbFcDcpbvcLcvbxckcec6bXcvdndjbOdjbCcWbScCb8ducAc7bSdabUcbbSdnbbcyb4c5b5cCcrc8cpcNbPcjcqcdcdcPcAbKbPcVbscHcJc7cibJcjddb7bLczdxbnbAbRc0bKcAc2dzcedpdrdobMcKdadJcJb5cQcRb9b8clcAcOcuchcvcFcrceckcJclchctcGcfcmcqcDcycgclcKcqcdcicLcAcib7cIb8chcwcOcdckcQcxczcgcRcNcpcocIcSclclcxcHcecmcBcNcmb7cjcNcucecDcvckcjc8cQcvchcLcFcacfcycMcLcmcHcFcicjcoc0b2chcBcEcrchcycvceclcycBcycqcPcBcccicQcMcjclcBcK), nameof(w1_b8cocrcRb0clcVcEcfcpcycyb8cocIcscIcgcMcPcdcFcncBcucfcAcWb8cAcocEb4cCcvcrcmcAcEcBb5cjcwcKcucicAcEckcocecFbZcxchcybVcocrcEcwcvb7cMb4cwcrcIcDcxcicTb9chcecCb4crb2cTcfcpclcObVctcecUb8cOb0cFclcfb_cMbYcjctcIb_cpcncIckcRcfcQb8cRcccGb7cOcccIcdcicucVcicqczcWcecmcvcLb9cfb8cBb6clb7cEb0cqcEcZb7cpcBcRcecocncRbZb1cqckcackbKcvdbclbKcnc9b_bUcfc8cobIcscZcrbLcIdbcBbNcPc2czbUcwc2crbHcLc3cybPdecLcibWdocyczbNcMcOcobGcyc3cobib1drchbEdecEcvbXdacPcibBcTcIcUbKb4dibpbHclc0b2b8cBc3cicacKc4cbbcc7dpcfb1cWcDcgbMcAcOcmbzc7cxcB), nameof(w1_bRcZcVcvcscqcRcgb8cdcKcdbRb_cbbScudhcrcLbocHdmbtb9deb4cCcgcrcochcrb5cGbWckcOc0b6cfcEcAciclcecDctcucidnbIbQcCdhb6bLb8dlb8cAcwc4czb9bzchbIckcDc2crbYcbdfbJb9cscicacfcQc8cEclb1cOb7c1cbdcbycub6cLbVcubZcUbQcxbpcIbjbubScOcnb9cxdncjb8cbcIcdckcndeb0cnbIcpbAcFcmc2bWbVcGcTbVbNcodabsbOb5cKb3b3cAdnb2b6cSdqb_bPcGdrceczcucWbqcgcoc7bicOcqckclcndcbtbYcdcobTbVchcycEbWbUb7cCc9bSbAcKdKbKb4cZdGbJcjcVdjcacfc9dpcfcQbIcCcocyb_cMb_cJb5cLb8cScwcTbZcdc8cYbKcrdscVbJchdVcsbNcEedcCbDcDbBcBcmcKcqcObWcmcPcTbYb1cXdcbQcidec3bPcq), nameof(w1_dtc7bVcedFcPcwcRdlcLcIcMbGcyb8csb4cIbScIcwcTbPcMc_cUbIcscYc2b2cIc_cQb6cGc6cUcrc2cJcJcXcRb7cubVcDcccIbQcXcrcObVcDcNcLb2c2cVcOb4cTcTcmcBc9czcPcOdecCcHc6cxcdb8b4cQcgcEb6cLcNcabRcScPcsb0cRcLcicnc9cscrcPcYckcXc0c0b7cVdHc3cYbHbLcWcYbUbQcGcNb6cfcKcUbVctcTczcccLcScecBcPcFb6dccZcQbFdmdBcBchcdcuchcFb5ctb8cAcucfcWcucacIclcGcccOctcWb8cSbKc_cPcSbJcBdgdabYchbUaVd0chcWc4cRcrcUc7cWcncscXcacdcucUb0cic3dhc_cccKcFc3cjcGc3cMcibMctcycicecZcacdc4cocncucWcCcoclcQc9cPcycTcScBb4cdckcBcpc3dxcwcicfcMb8chdib9b2b6cVcsczcxcI), nameof(w1_cMctcnc7cNcvcpc6cAcdcgcGb0bCcucTcncDcAcYdccQcoczcmbHcGcvckckcocFcycecuc4cocQcKcVb7bObScKcZbPcJcDcIbZb0b_cvb8cnb4ctb1cIcncNcvcPb6cEcbcqdscjcfb5chc8bTcPcicDckcccHcHcacxchbXbRcocec9cpcJcccAcacCb5cWcEcYbBczcKcebHcRbRcgbQcLbMcKbsdnbOcmc1c_bRcRcoc2ctcUcecXcbcGbEcibkczcucGclbJcqc3cnc7bKcObycJccc1cjcLb3cTccckb6cUcgcqcvcOb8cbbOcHbIcfcrc7b5cBcNcXcccmbEctbrcxcccvbMcmcbcHbQb6cIctcfcdbJcfc0ckbTc2dQchbDb8cFcibPcRdicrb1cZdNbTbnbRcxcwbPcBcKdabDcuc5cXbycKcfbZbocNcuclb9dpcYc0bZcHcPcMbDcIc0cUb9dpcncPbPcXb5cYbQcMck), nameof(w1_crbTcCc9cbbXcsdabWcrc0cKcyckcUcJb0cmcPdbcZbYcQcQcva5c_cubWcBcYckb_cwckcDcvblcKc9bRbLb8c0b0ckcMcOcZcmcHcpcob3cQcdcubEccc3b_cpcsc6b_cDcgcmcibKcpcwbCb1cicGbBckcocNcgbQcgdubPcNcMcJclcQb9ducncub8cXcdcBcBdBchcPb0cucvb3b4cEb8cpcgb8bNcTbwc5b0ckbEcZb_cscac5bBbZb_cAcnb3bZcRbBcKbwczb6ctbRcMcgcscRdgcRcmbScPcbcebYc3bIc7bKcQcjcxb4cEb7bUcJdocrcfcJdlcocncucRckb0cUdkcEclcDdnbBbzb4cWb3cYcScPbIcAcPdnbGcGb2cOb1bNcdc6dDb4cAdldIb2b_cGdbbWb9cQcOcdcbcKcJcLbZcZcPcMcebZbVczb2bpb6bXbVcedLbjbKbKdlcEbvbKdxcrcocCcAb3b8crcbb7), nameof(w1_b9dcchcpcRdpbdcBbodyaacqbrbXdMcMbHcLcFbSb7cFccb6bJcxctcxb2chclchbXbHdpcmchc_chckcpdzbtc0bZcYcAcccccAbTddcucxcUcwcqcmcicCcrcncxc_bwcCcAb8cJcqcvcWdvc5bKb5bLc1cRb6chcBcxcjcfbZcAcscCcvbTcwcRb1b2bLbbcodAb9cobXc2bRducLcMcSb3cPdAb9cectczbDcucxckchbYcHcTbIcgcBdbcrbxbWc9bZbQcedCbLd8bRcgcjb1cBdmcnchcMc_b9cGbYdabUcccOcPcgcgctdecccpcnc7cEbTcbcZaOdGcqcEcjcccZdBcEcYcDc9cccjcAc4ctcgchdfclcQcTdebVbVcMdqcocGcLc_b2cUchcRb7cYclcIbSbabVcUc_cQb1c_dacSbVcAcXb_cfcDcVcsb1cXdecMb4cvcTcQcdcOc7cNb8cIdrcdbKc1b3cKb3cUcvcubu), nameof(w1_b6cHckb7bZcCcBbVcuc3ceb0c4cxb8bYbZcNcTbMcZcecFb5drdmdbctcZcAcqbFcRcacucicScOcob7cTcpcwbvcacXcDbSdIc5c1cecFcTb5cncRcEcRcxcjcsb9b_cYc8b_bZbOcycfbHcXb7cobRdpcOcCb9cTcNcrclcwcCb1b7c0c3cFbKb_cObDcQb8dDcbb2cTcocxbVb4bNcAdfcKc8cnb4cecEbOcycscgcLc0c6dyclcfbQc1bLcubFcTclcHbTdbcnccbldkcbcycdcHbYczcIdecWdNbVcUchcOb6cNcccPbUcsbScjcnc0cscjbRdrb0cEbQcRbYdfbVcxb9c0bscncNcecLc3bubJbVc6cjbZcmc_b1bVchdbbJbMb6cZb1bRb8c5bXckbScrbictcucRcucMcEcUbCcqbtcaccczcucWcyc_cgc8cAcZchcWcxc4cpcMcyc5ckcNcAc1ccc4cAc_cnc4cCcZcDc8), nameof(w1_cIcWb0cZcAcYb2c7cwc5bXc3cAcYbYdncrcQcfc4cvcWcac4cscYcbcYcrcZckcTcDcQb9cTcDcZb4cXczc1b1c3cAc5bUc3cDc0cacYcAc5cicVczc0cmcUcDcXcjcQcGcPcacIcwc5ckcMcEc5chcQcCc5cmcPcDc_cscMcQc8cwcScEc2cncRcOcWcocOcHcUcmcLcvc4clcHcJc0ctcOcFc1cucEcKc9cycKcJdbcAcJcQddcscIcPcZctcNcEcZcocKcnc4czcJcBc1cycKcDc3clcHcNc6czcLcFc_cDcGcNdccAcHcFc7czcFcIc4crcScddacucScec2cgcZckcWcwcYcpc5cqcTckdacDcWcnc2cxcPchdbcvcUcic_cMc8cbdecAc0chc_cFcVciddcFcXchc_cxc5cfdbcGc1cldicKcZcdddcLcWcidcb4cAcVbEcZbZb8cRb5b8cHc5b8b5cqc9crb4clcScpcdcEcS), nameof(w1_bYb9cCdib1bNcbcIcob0b4cJb_b8dscicibXcqcKb5cjcAc5b5cecJc8ctcgc4cJczb6cXcCcrb9cLcpcwbScOcacDb2cvcPbWchcQcnb9b3cXc8cpb2cncUcwcecPcPcmcqcNc_cqcfcPcPb4cecIddcicdcVcxcjb8cvcHcfb_djc8c1b2cMcTbSbXdacGcrctc9cTctcNcoc7b6b5cqcDcrckb_dgbNcgcqdjbPcbb3c7bSbCcKcbcfclczc8bVcDchcPbZbPc0cSbHcobUc0clctb7cBb9cbcldhb5b1cjcvbscvbUcBcccsb8cIb9b7cecGbXcHcgc4cfcmcmcKcscJb3cEbUcEb1cGbYbYcscOb3cncdcwb3b1coc7bZcRcccXb3cIcmcJchc2cfcPbObZcfc7bDbCb8c3b9bwbZcGbIcccwddb7bNbNczbBbLcac9bScCc2cZbHcDc2c7b2bTceb_cXczbWcYdbc0bOcjcScs), nameof(w1_bTcbc5bWcccMc3clbYcHc7cnbZcSc8czb7cacScpbRbNcHctbZcIc0cacndKcycEb3crcWb6bPcqc1b_bRbUdkbKcqcYcdbPb5dvcNcVcac0ctc5bIddcSbTbTcoc2cjb6cRdacsb1cacPbZcfdrcUcXcBcAcccycfcYcccVbNb7cVcucsczcRccb4cvcIcbcAcKdtcScmcKcRb7bZcCcPcjcncub6ccbyctcJbRbCcuc7cmcbcvczclcaczcmbEc6bPcHcncpcxczcBcHcYcEcYcUcSctcicicscAb6cxcJcDcfb6cVc7cdcHcpcJcpcrcrc4cucabXcEcccIb4cCb3bXclcqcgcEcicZcacubQcVcdcMclcScocPbQcTb3ckcoc7cwbRb4dpcxbNbTclbPc0cacWb3cLcFc5bucDcmcRckb1cuc1b7bXbXczbBbOcpc1cpbTb4cwbGcdcMdhb1b7ctcYcicjbHclbkcqdhdmchb1cm), nameof(w1_cjchcKcmdbc2dib4cLcBcXcdc4c9cZcncNcUctcDcCcwc4cgcAcSc_clcRcYdicuczcGczbMcVc7b8czcycHcDcscJb9cJcycNcOcxb4cdcyc8cAcjcucxcjcNbYcRcAcYbTbQbKdqcQcbcUcXcrclcybXcvckcAbEcucpchcfcicHc0c1cwcPcwc_cgctcMddcfcFbYdCcBb6cscpb9cnbWcecfcRbLb2cGbPb_cicMcab2b2dbbQcQc1cFb5czcUcwb4bLdccAcdcocEcicAclcrcdbPbYcyckclb_cob_bMclccdmbMcfbXdebKcDdvcEbxcQcmcFcPctcecLb9dcbZcLcucZb6cXcMcxbzcZcbdbbTcZbNdHbvdbctckb1dpbQdhclc1bvcAbNcUcrcIb1cEb_cubVcRcdcYbUcwbSdXbHcFczdna_dmcmdqb7cyb_cCcicxb3cncfcMcfcuckcyb9b4cqc9cObTb6cEcmbRbQcq), nameof(w1_cCb4cscIcEcBcGcqcFcwcecib0b3cjcqcVchcfb6cIcrckcAcOcbcmcNc_cychcLcYdpcjc0cXcYcfcvc0cycgcScZcHb8cTcJb9ckcIcQcichcccMb6cdcJcEcMcecDcHcAbQcCcnckcpcucJcTb4cycucucec7c1cHcec4cybAcgcycKcdcrcIcPcDcacmcDcmb9cycFcgcocKcJcccacMbYcocucNcmcrb7cwcjbLcdc8cRb6cdctcycwcgcicMb4b3b_cjclcdcGcwcacEcFc5cDcaclcCcicqcIc0cicCcbcEcLcsclcVcecDb0cKcjcGciciclcmctcBcicscrcEcdcDb4cJcvcsb0c2cjcncldccRckcxcJckcpcXcOcCcncpczcpcyckcMclcGcmchb8cBcicJchb8cucXcvbNcfb6bPcjb1ctbycpcwc6cEcPb_cLctclcocpchcOb9cyb8cdbVcubDcdcwcDb5cgchczb9), nameof(w1_b7bWczbPcccfcDcub9bwclbDcXcVcRchcbcncOcacncccbcvcLbAcbcRckbIcAcVcwb7cDcQcDbPcmcKckb6cPdAcFbNcCcAcDbnb6cwcbbUclcTcobScQcwcgccdvcKb7b6cDc6cAbZcKc7cab3cAcTckbKcJczcEcmdob_cybNcxcccYb3cXcNcbbUcRcpcjcdcJclcDcUcZdVcgbWc0cEcdbsb9cQcpclcUcscfbLdacAcGcucKcFb4bCcMcVbrcTcbcPccbYb9cNcecvcHcBcscgcOb9cvcAcedfcyclcJctcsb6cMdqbAcqcoc3bWcNb6cIcKbGcOc2b3cwcqcfbUchb1cSbQcJcmcUcwb_cVdicoc_bWc6cfc5cUcScucmcJcTbxcOcCcNcScmcudncCclcBcNbRcQbNcGcvchb7c5b0cZb8c8b6b9crdjb3bVcjdgcwcxcpcPbOctcnc6ckb3b3cWcab9bKccbfc0bEcrbVbw), nameof(w1_b4cWbZbZb8cWbObVcjcYcmbLbRcEbwbRb0cHbtb0cdcLbQcvb2cCbqbObJcXbhbXb7cccncfb0cqdockbUcjcpcEb6cGdfclb8b9cYcfb1cecOclcfcHdfcIbTcgcXcsbYcncYb7b5cPcWbXbWc8clccb3cwcScnb7cncEclb4cCcUceb_cMczcmb2cUcFcrb3cCcGcmb5cYcPb1b1cPcyceb5cDctb6b_c1cNcEcecvcIb7b1cUcZcacdcEcycib2cNcNcocdcFcGb1cucyc2b5cecFdbbWb6dacIbYcac1cObUcscpcJb1bZc4cRb6bVcYcXcwcdcdc8bAb2cMcMb4cycOcGcFcdcjcDbHcgckcycpb8cCcVbHcycMcEb3cxcscEcfcdchdbb1csbSdhbHcOcgc4chcPb8cRcaclchc2cdcjcpcJcscAccc4bZcIb_cSbRcOb9dsblcCb3cDcncBcdc9bTb0cwcUb1cjb_cIbEcAbY), nameof(w1_dfcaccbIckbPcQcuc1b2bScbczbNcichcSbHcucrcVbSb2chcJbYbYcDc1b5b5chcZbRcwcxcTbHb8cfc2bLcTcncnctcpcGb3b3cecUb1b4cccXbXbWcecXb1bYcacVbZbYcbcWb4bVcec0b4b3cccJcfb3ccc3bKb8ckcYbMb_coc3bJcacicSbQb4cec1bIb7cfcVbKcccicWbNb8cccUbRb9cccMbTb9cdcKbPb9cdcNbPb8cdcLbJcecicIbNcacdcJbOb8cdcMbPb8cfcGbTcacfcFbWb_cdcFbTb9cdcEbQb8cbcEbTb9cbcAbQchcbczbTcbcccAbWcbb9cDbUb_cfcFbYcbb9czbRcib9cEbWcab8cCbXb9b_cwbZcib8cBbZcfb8cAbSciccczb0ceb7cAbQclb8cAbPcmb9cubPclb6cqbRcpb7cAbRcmb8cwbVcmcccybScjcecwbTcocbcCbPczb4cDbKcub8chbRcv), nameof(w1_bYcubSctb3cubRcpb_cEbVcob9cBbXb_ckcwbTclcccrbYcmb8cFbPctcbczbVclb8cvbUcgcccwbScrcbcvb0cncbcJbUcncccnbZcncbdccGcGb_cbcBcTcPccbKc5cucnbwcEcYctbNcWddcfbQcNc_cjbUcGc4cmbNcEcrclcwbXb5b9b2cNc3chbLc5cHcmcicUcKcjcbcLcZchbYc7cNchctcWcEcgcPcRcFcDcdccdecXcycFcJcIcmc8czcecuc0cJcjcIcVcXb6czc5cCb3cqcZcNb9chc2cwcectcDc1b2cScEcvcAcBcPcvcucOc6cCcccKc5cNb8cNc_cCb3cUcWcUb1cMcScBb6cAcxc_b4cMcucvcZcUcRcuctcAcJcycucHcMcHcrc_cVcscncLcQcHcacLcFcXb2cjb6c6coc5cQcmcOcXcSckcXc6cScdcXcLcIcAcxcGcLcHcrcXczcycNcbcScYcob2csdecq), nameof(w1_c7cKcvcWdncLcrcZdhcMclcUc4cLclcZcHcLclcKcvcMctcOcrcPdfbRbTbGdxcScvcNcHcJbZdmbZc9cec8chcOcscVcocXb2dmb0c4b5dbcmcEbzcbcMcZbFbQcwdpbRcacqcxbZcpcycKcrcqcncGckcncpcAcfcmcHcDcmcqczcMcgcqcAcBckcjclcDcGcpcscKcycpcucOb6cncycxctcqcScOb_clcLcGcmcpcDczcwcgcvcrb1cicLcmcuclcHcecvclcycBbTcrcScIceckclcxcwcmczcGcfcncDcCcpclcGcEb_cocHcrcccmcxcycpcmcVcDb2cuczcDb3cmcDcEcecpcFcBb_cqcrcJb_cpcscDcecpcGcwb7ckcNcCcucyckcvcqcqb9cCb_cncrcBb9ctcJczctcxcecMb_cqcmcHclcpcvcGb_ctcwcwcfcocacKcacpb_cCb7ctcycIcgcpcocFcfcvb_cFcacm), nameof(w1_cjczckcIbYcOcacub6cGcicmcpcMcccvcicLb9cockcEcococtcFcgctb9cIcgcFb9cTb7crcicAb1cJcfcycecjcjcQb7cqcocMcdcpcocHb_cmb6cAbWclcpcFclclcicLcdckcpcEcdcpcqcEb1cscrcuckcncscGcBcLcEcocWcNcmcAcHcBc9cVb_cwdhcOb2cpdxc1bYcedpczcDbVcAcJcNbJc5cKcoc9cocBclddcJcub5cSc2cMbFcDc9dabDczcwcPcbchcuc2cvbIbYc_cnbCcfc4cvcXcacCcCcLcYcAb6cPcKczb6cNc3cGcfcsdlcMbXcdctcYcfbKcocZcnbkckdbcxcLcnc9cIcqcbcEcscAcdckcucTcbckbXcLcrcnb2czcdcCb4b5crcLbZbDcydmcMb8cadlcqcDbZcOcNcKb5cncAcqbXbYcHcHcsb4cjcfctcecccab6cob3bTckdtcvcdchdncBcbb9cK), nameof(w1_cOcycgcfc4cycocddab2ctbVcZbUcVb0cwbFcrb_b8bQcqdGcEb4b7dfcGcecwcYcRchbWc2cIchcobWdxb1cGbFdqcgdqa8drcocIa5c2cddrdhc4b2d_c7cNcAdWcUcwc6cFcNdgbZbPcAdmbVb2b2dtcscibXcFb8ccbXcKbEcTa8cYctbbbUcQc9ckbHcjc3chbScVdBb3bHcYc0cyb4cBdfbMbTcbc9cabQcNc6cLbJb8cWcMbQcDcIcjbLc5cbcfbKcqdjcEbQcAdecebIcncVcfbXcLcXcNbKcuckcMchdWc0cTbLcMc6bKcdcldaceb8cscochbSb9dkcychcQclbZbOcRc6cvbNcMclcrbLdcchb1cBcXcTcBb6cqcKcdcrcedjctbkcGcOcebTcIb4cqcQcKb7b1cUdec5cobIc_ctclcVcycGb5cGcicHcEcwbOcxb1bScfcGcbcHcwbWcmcocYdAczb_bZcNb6b2c2dj), nameof(w1_cicncWdCckbXb9cWbBccbVcGb3cGbBcFbKcRbHc9cgcIb1cVb3cicAdlcidfcjc1cdcyb7drb1bIb6cDbtclbZcUbUbJbPcNb6b8bFcNb3cYb_cBcidcbJc1bVc3cbcVcgbEbXcYbKbYcLc7cgbNcdc_cqb4cpc9cmbXcLdfcwblbYcPcgc7dgdmcpb5bVcSbJb0cecvclcv)}, 32, 261, 18, 44.602638244628906);
// int b2_a_ckdIcgdibMbkeda4aBbjaPakbGajc6bqaaa1aqdXauaFccbAarafdAdIb1cYaj;
// fc_biases[0] = LoadParams(new string[] {nameof(b2_a_ckdIcgdibMbkeda4aBbjaPakbGajc6bqaaa1aqdXauaFccbAarafdAdIb1cYaj)}, 32, 60, 130.22149658203125);
// int w3_bUcCb1cabpbEbcbEbzcLcKc8cccqcfcnckcncocTcUdmc8cIcoboclc2cscHccc2crb9cncecfceb_cbb5bTcBceclb_chcjcicpckcqcmcfb5cacgcccecmclchcicAcycmcbcgbZb6chb0ctb7cacDckcicpcwb7cgcncwbYcxcmcccqchcibGcbcjckcwdkcybtcucXcmbIcZdrcwbUb9cSbUb8cmaicqcqdwcidfczc8dBdMdzbNb9cCckddcccfckcqb2b1ckbKcucacgcecpb3ctcmcycicob4ceclcicucpb7cobBcdcxb6ceb3b8bncdb2bLcrbRcub4cvcxcEcsclcpcvcrcucnbEctbRbxb7cicib9cCcbbWcxcqbKbIcIbvbUccbJb7cfcgcic9ckcrcCcscvb8b2bFcIb4bXb_cvcubIb2cwcib9cxcecJcrdBcJcXcGcRdpcwcucncDdScwcqaXcNcecjddbTbTb8bN, w3_cSb5cFb9clbXcdcAbZbWaNaabQbsciceb7cLctczcqcvbZbHbIbWc4cLcJcXb8bkbIcUcycfcrcob7cub6cucbb1b5b7cbcqb_cucjb5cpcscsczcqcmb4cjcbcuchb6b6bRb3b_cccsb5dnbNb9bMbRb4a4cecXcpcucbb6cibPbUcsdpdsb5cwbxcqcecib4bsbRb8cnclchcob7cvb_b1cobTcdb9b7cscmcdclcgb8b5ctcubFcrcvcpb_cicDbYb6ckctcwcycjb5b9b9b4b_b8cgccb8cwcbb6b_cfb9ctclcnb0cmcrcscccgcebZcccvcpb7cpcrbbcpb0bUcpa_cxbMcacxbOcsczbkcichbscEb5cLcad8cvcicsbubccpcnbFcccKcEc_aYbVcHcgbredc_cwdebnaTbZc6a6cWcqbGb5dkcacyb4bKcCbUcpdkdlcib8cjbRcfbccxbTcvdCcAcFcjb_cnctb9cfcdcf, w3_ckcqb7cbcab3cvbWbEcjbVchccb8cicgcacmb9cmcocacbcfclcmb4cbcpcccqcccaclb6cbcjcmcob7cjcecab7bBcdb0cjcWa3bBbmc5bybQchc0dkbxcmbIcpcGaMduc_cwb1b_ckbTcobGb8cucUbscPcRcmbvcrczcbbOcVc1cpcocScBcqctbOcQcWcacDbRddcqdhcFdicqcqbZczcqcDcHcSbhcucScacac8cpcucScabycicnducMcpcicKcrb6cncLcNdmcgcVc6c0cwcpb5b8csbSclcab3cqcmccb_cpb5cqctcocgccbPchcecccacvcsb6bGb6cmcocxcbcLccdpc1bLbzccbBcccEbWckcsbBcscycgchbNcBcpcib8bRcocFcjcucjccchb8bTcIccbob4bPchcgclcxb5cucib6cxcob8b1bwb7b9b0b5cmcnbCbWcacCcpcubOb7b6b7cccgcycAcncgckcncm, w3_cuchcicEchchcacBchcdcycycvbTb2cobAcbcob1bXb_cTb0bjcVcjdmcwb5doclcfcob2bpcrcGbZcTcXbQb2dBdbcDcjcub6cxcichbUbQb4bRcza2cwb_c2cpcmcyckcbczclcjcpbqcncfcccfcscxbubTcxcccjb4clckccckb9crcacwb6cacncdcnclcccuckb3crcncxcgcpcnchcnb0cncocmb9cFcHdecqcScecFcgcecncHcwcBcmcKc0cbcgctcfc0bNcecMcGb6b6cbcXchcrcrcobScXbBbYb_cbbPbQbBbXcgb4cebWcbbxbJbXckchceaicecndacNc1cmcebZbQcHcab9cpbGb7cgbTctcbckb5chcub8ctckcpb9cxcdcwcmcscrcucabVcjcwchctcxcabVcEbBctcdbHctc3czcocecnbUcqcscibMchcqcccackcfcncsbNbVcxcFcgcfb5b0cmb7aXb_bA, w3_cvcmcccccqczchcsclcmcaclcscvcrcicccvcobVbyclcjcx;
// fc_weights[1] = LoadParams(new string[] {nameof(w3_bUcCb1cabpbEbcbEbzcLcKc8cccqcfcnckcncocTcUdmc8cIcoboclc2cscHccc2crb9cncecfceb_cbb5bTcBceclb_chcjcicpckcqcmcfb5cacgcccecmclchcicAcycmcbcgbZb6chb0ctb7cacDckcicpcwb7cgcncwbYcxcmcccqchcibGcbcjckcwdkcybtcucXcmbIcZdrcwbUb9cSbUb8cmaicqcqdwcidfczc8dBdMdzbNb9cCckddcccfckcqb2b1ckbKcucacgcecpb3ctcmcycicob4ceclcicucpb7cobBcdcxb6ceb3b8bncdb2bLcrbRcub4cvcxcEcsclcpcvcrcucnbEctbRbxb7cicib9cCcbbWcxcqbKbIcIbvbUccbJb7cfcgcic9ckcrcCcscvb8b2bFcIb4bXb_cvcubIb2cwcib9cxcecJcrdBcJcXcGcRdpcwcucncDdScwcqaXcNcecjddbTbTb8bN), nameof(w3_cSb5cFb9clbXcdcAbZbWaNaabQbsciceb7cLctczcqcvbZbHbIbWc4cLcJcXb8bkbIcUcycfcrcob7cub6cucbb1b5b7cbcqb_cucjb5cpcscsczcqcmb4cjcbcuchb6b6bRb3b_cccsb5dnbNb9bMbRb4a4cecXcpcucbb6cibPbUcsdpdsb5cwbxcqcecib4bsbRb8cnclchcob7cvb_b1cobTcdb9b7cscmcdclcgb8b5ctcubFcrcvcpb_cicDbYb6ckctcwcycjb5b9b9b4b_b8cgccb8cwcbb6b_cfb9ctclcnb0cmcrcscccgcebZcccvcpb7cpcrbbcpb0bUcpa_cxbMcacxbOcsczbkcichbscEb5cLcad8cvcicsbubccpcnbFcccKcEc_aYbVcHcgbredc_cwdebnaTbZc6a6cWcqbGb5dkcacyb4bKcCbUcpdkdlcib8cjbRcfbccxbTcvdCcAcFcjb_cnctb9cfcdcf), nameof(w3_ckcqb7cbcab3cvbWbEcjbVchccb8cicgcacmb9cmcocacbcfclcmb4cbcpcccqcccaclb6cbcjcmcob7cjcecab7bBcdb0cjcWa3bBbmc5bybQchc0dkbxcmbIcpcGaMduc_cwb1b_ckbTcobGb8cucUbscPcRcmbvcrczcbbOcVc1cpcocScBcqctbOcQcWcacDbRddcqdhcFdicqcqbZczcqcDcHcSbhcucScacac8cpcucScabycicnducMcpcicKcrb6cncLcNdmcgcVc6c0cwcpb5b8csbSclcab3cqcmccb_cpb5cqctcocgccbPchcecccacvcsb6bGb6cmcocxcbcLccdpc1bLbzccbBcccEbWckcsbBcscycgchbNcBcpcib8bRcocFcjcucjccchb8bTcIccbob4bPchcgclcxb5cucib6cxcob8b1bwb7b9b0b5cmcnbCbWcacCcpcubOb7b6b7cccgcycAcncgckcncm), nameof(w3_cuchcicEchchcacBchcdcycycvbTb2cobAcbcob1bXb_cTb0bjcVcjdmcwb5doclcfcob2bpcrcGbZcTcXbQb2dBdbcDcjcub6cxcichbUbQb4bRcza2cwb_c2cpcmcyckcbczclcjcpbqcncfcccfcscxbubTcxcccjb4clckccckb9crcacwb6cacncdcnclcccuckb3crcncxcgcpcnchcnb0cncocmb9cFcHdecqcScecFcgcecncHcwcBcmcKc0cbcgctcfc0bNcecMcGb6b6cbcXchcrcrcobScXbBbYb_cbbPbQbBbXcgb4cebWcbbxbJbXckchceaicecndacNc1cmcebZbQcHcab9cpbGb7cgbTctcbckb5chcub8ctckcpb9cxcdcwcmcscrcucabVcjcwchctcxcabVcEbBctcdbHctc3czcocecnbUcqcscibMchcqcccackcfcncsbNbVcxcFcgcfb5b0cmb7aXb_bA), nameof(w3_cvcmcccccqczchcsclcmcaclcscvcrcicccvcobVbyclcjcx)}, 32, 32, 11, 90.39102935791016);
// int b4_edcQcTbVc1ccbUcjdmcVbLc_cvchbXcmcscxd6d5chaabXcAbVcqc0dAcqcYc0cS;
// fc_biases[1] = LoadParams(new string[] {nameof(b4_edcQcTbVc1ccbUcjdmcVbLc_cvchbXcmcscxd6d5chaabXcAbVcqc0dAcqcYc0cS)}, 32, 47, 120.5653305053711);
// int w5_dvcEcHdhcKcIc3cuc2cQcVcUcIdadwcXcQcOc7dicOckcucTcTcZcRcIcJcUcKcIcscZcOcCcTcQcCcccDcTc7cVcXcKdccKc1dHdycZcFbscJcBcmdbcJa7cCcTcWcWcqcRcAcfczcycJb7cycIcYcHcQcEcLcNcHcJchbZc5csc4cMcmcIcAcwcbc1cDcScQcScPcmcVcDbxbYc6cRclcBc2cmcEcucFdodddkcSa0b2drcGdhcJcrcScFcJcLcTcNcHbRcEcJcDcycoczcPb_cFcGcbcFcMcHcpcOcXcGcMc8bTcJcJcCcoc0cMcMcRcNczcocDcEc4cucHcHcMcNc5c5ckczc4cucBcccMcAcTcXbQcLcEcJcWcWcQcNcWcvcPcDcScDcIb8cVcMc1cYcJcLcEcFcTcrcOclcMcpcycGcVcwcQb_cGcLc0cBcvcEcYcNcRcYcPcAcBcNc1c1cQc4b9cZcMcUcGcscVcXcYcKcKcQ, w5_c5czcLc5cXcScucQcYcocOcVcYcFcOc3cJcZcKcGcfcZcBcyclcwcWcUc9cFcZcGc0cocEcXc7cEdgcYczcKcwcWcXc7cLcCb8cWcVcEdqc1dcdNb3cIc3bBcTc1dccjcPcPbVcYc1cxcCcHcEcEcXcFcxcNcQcJcScMcFcXcKcGdhcvcDcIcCcOc0cGcVcKcScHcYcvc0cWcScXcOcAcUdfcJcNdlcxbKcEcRbWc6ckczc1cGcpcEcocWcZcUcscSdtcgcKcvdcdrcUcYcvcOcfcQcedocPcHcAcVdocPcEdec_c_dfcPbWciczcRdbcFcFcJcSc4c7cwcucQcQcAcvcIcycvcEcZctcPcJcEcOc0czcxcvcKcDc0czcIcKcQcncOcTcJcMcLc4cZcFcJcVcYcMcQcNcCc2cOcPcxcUcMcxczczcXcRcGcFcMc1cLcGcOcYcOcHcMczcZcxcUcMcMcAcZcRcPcTc0cFcRczdccNb0ck, w5_cEcxcvcCcGcEcTctcOcvcScNcCcNcLcRc5cMddc4cVcScHcXcRcWcocYcvcKaaaRc0duc1drbYcrcYc0dFcRc1cHcxcwcvcHcScCcTcFcOcPcYcQcUcDcCcWcVcRcKcLcGcXcLcRcFcvcPcBcIcCcRcCcZcYcGcvczcScucCcPcscFcIc0cEcHcPcwcCcycFcKcHcYcIcAcGcXcLc1c3cJcQdyc2cTcPcKcucyb2dGcQcPcYcycScTcZdbbZcVcycYb0b6decqcDcQbMdwcQcIdacqcXcWcpcucJcxczcBcUcEcGc0cwcscKcEcIcncFcJcPcFcUcEcBcwcvcXcHcYcLcTcFcFbJcFcydscDdicHcVdqc0cZbVdwcWdzbJbxcwdGcjcsbQbucEc8dBchc6c0decIcUdmcVcWcOcgedcHcIcScycEcycbcHcCdoc3cQbGcOcZcSb1cLbVcSctcUcVcLcYcCcTcJcOcScycCcCcDcSczcz, w5_cLcLcDcDcLcOcYcAcJcFc3cYcFcAc3cFcTc2c6cLc3b5cKcTcJcPcAc0cTcPc_cMc1cJcQdDcicfcCdvcJcScJcqc5dscnc2cPc3cycVc7cbcUcOcvcNcEcVcWczcXczcRcxcEcKcrcCcZcBcGc1bTcIcvcSbRcCc1c6b7cucTcAcTcFcUckclcJcOcNcPcucMcXcJcGcccwcucKcOcxczcVctcrcQcAcDctcCcUc5bPcUcIc_cCcOc8c3cZcEcJcQcOcRcDcHcCc0cxcEcRcBcRcWcEcMcJcKcScucYcPcCcXcTcVcHcucOcrcZcKc5c3dacOckb_cgcEcscscRbQc1cQdeclcVcYcIcPcTbUcCc4cNcdcrctcjbwc1cZbFcscKcKcxcScGb7bKcjcPcrb3cRc6bOc6cQc8dacLcwcrcBc_cTcNcXcYbUcCcJcJcicncOdJb1bYcnddcDcvcdcfcQdqcncUdDc_cJcDcIcvcUcGcQcw, w5_c3cQcScQcZcWcbcWcAcPctcMcUcSc6cVc0cQcJcBc2c3cMcH;
// fc_weights[2] = LoadParams(new string[] {nameof(w5_dvcEcHdhcKcIc3cuc2cQcVcUcIdadwcXcQcOc7dicOckcucTcTcZcRcIcJcUcKcIcscZcOcCcTcQcCcccDcTc7cVcXcKdccKc1dHdycZcFbscJcBcmdbcJa7cCcTcWcWcqcRcAcfczcycJb7cycIcYcHcQcEcLcNcHcJchbZc5csc4cMcmcIcAcwcbc1cDcScQcScPcmcVcDbxbYc6cRclcBc2cmcEcucFdodddkcSa0b2drcGdhcJcrcScFcJcLcTcNcHbRcEcJcDcycoczcPb_cFcGcbcFcMcHcpcOcXcGcMc8bTcJcJcCcoc0cMcMcRcNczcocDcEc4cucHcHcMcNc5c5ckczc4cucBcccMcAcTcXbQcLcEcJcWcWcQcNcWcvcPcDcScDcIb8cVcMc1cYcJcLcEcFcTcrcOclcMcpcycGcVcwcQb_cGcLc0cBcvcEcYcNcRcYcPcAcBcNc1c1cQc4b9cZcMcUcGcscVcXcYcKcKcQ), nameof(w5_c5czcLc5cXcScucQcYcocOcVcYcFcOc3cJcZcKcGcfcZcBcyclcwcWcUc9cFcZcGc0cocEcXc7cEdgcYczcKcwcWcXc7cLcCb8cWcVcEdqc1dcdNb3cIc3bBcTc1dccjcPcPbVcYc1cxcCcHcEcEcXcFcxcNcQcJcScMcFcXcKcGdhcvcDcIcCcOc0cGcVcKcScHcYcvc0cWcScXcOcAcUdfcJcNdlcxbKcEcRbWc6ckczc1cGcpcEcocWcZcUcscSdtcgcKcvdcdrcUcYcvcOcfcQcedocPcHcAcVdocPcEdec_c_dfcPbWciczcRdbcFcFcJcSc4c7cwcucQcQcAcvcIcycvcEcZctcPcJcEcOc0czcxcvcKcDc0czcIcKcQcncOcTcJcMcLc4cZcFcJcVcYcMcQcNcCc2cOcPcxcUcMcxczczcXcRcGcFcMc1cLcGcOcYcOcHcMczcZcxcUcMcMcAcZcRcPcTc0cFcRczdccNb0ck), nameof(w5_cEcxcvcCcGcEcTctcOcvcScNcCcNcLcRc5cMddc4cVcScHcXcRcWcocYcvcKaaaRc0duc1drbYcrcYc0dFcRc1cHcxcwcvcHcScCcTcFcOcPcYcQcUcDcCcWcVcRcKcLcGcXcLcRcFcvcPcBcIcCcRcCcZcYcGcvczcScucCcPcscFcIc0cEcHcPcwcCcycFcKcHcYcIcAcGcXcLc1c3cJcQdyc2cTcPcKcucyb2dGcQcPcYcycScTcZdbbZcVcycYb0b6decqcDcQbMdwcQcIdacqcXcWcpcucJcxczcBcUcEcGc0cwcscKcEcIcncFcJcPcFcUcEcBcwcvcXcHcYcLcTcFcFbJcFcydscDdicHcVdqc0cZbVdwcWdzbJbxcwdGcjcsbQbucEc8dBchc6c0decIcUdmcVcWcOcgedcHcIcScycEcycbcHcCdoc3cQbGcOcZcSb1cLbVcSctcUcVcLcYcCcTcJcOcScycCcCcDcSczcz), nameof(w5_cLcLcDcDcLcOcYcAcJcFc3cYcFcAc3cFcTc2c6cLc3b5cKcTcJcPcAc0cTcPc_cMc1cJcQdDcicfcCdvcJcScJcqc5dscnc2cPc3cycVc7cbcUcOcvcNcEcVcWczcXczcRcxcEcKcrcCcZcBcGc1bTcIcvcSbRcCc1c6b7cucTcAcTcFcUckclcJcOcNcPcucMcXcJcGcccwcucKcOcxczcVctcrcQcAcDctcCcUc5bPcUcIc_cCcOc8c3cZcEcJcQcOcRcDcHcCc0cxcEcRcBcRcWcEcMcJcKcScucYcPcCcXcTcVcHcucOcrcZcKc5c3dacOckb_cgcEcscscRbQc1cQdeclcVcYcIcPcTbUcCc4cNcdcrctcjbwc1cZbFcscKcKcxcScGb7bKcjcPcrb3cRc6bOc6cQc8dacLcwcrcBc_cTcNcXcYbUcCcJcJcicncOdJb1bYcnddcDcvcdcfcQdqcncUdDc_cJcDcIcvcUcGcQcw), nameof(w5_c3cQcScQcZcWcbcWcAcPctcMcUcSc6cVc0cQcJcBc2c3cMcH)}, 32, 32, 39, 94.18290710449219);
// int b6_dXaRbQdjcPcicodacJa7cLebeacCc2cVaacUczbqcpcfb8cxdVcecDc2cIbYedc6;
// fc_biases[2] = LoadParams(new string[] {nameof(b6_dXaRbQdjcPcicodacJa7cLebeacCc2cVaacUczbqcpcfb8cxdVcecDc2cIbYedc6)}, 32, 44, 126.99993896484375);
// int w7_dWedaad2dYcGbucwcTdOdFcAd_bkeddObscRdbdSclcadOd4cpcYdJbVcIdfcqcy;
// fc_weights[3] = LoadParams(new string[] {nameof(w7_dWedaad2dYcGbucwcTdOdFcAd_bkeddObscRdbdSclcadOd4cpcYdJbVcIdfcqcy)}, 1, 32, 66, 577.11669921875);

//             nn = new NeuralNetwork(fc_weights, fc_biases, embedding);
//         }
//         int white = board.IsWhiteToMove ? 1 : -1;
//         int deepness = 4;

//         if (board.GameMoveHistory.Count() < 3) {
//             deepness = 3;
//         }

//         if (timer.MillisecondsRemaining < 3000) {
//             deepness = 1;
//         } else if (timer.MillisecondsRemaining < 10_000) {
//             deepness = 3;
//         } 
//         else if (board.GetLegalMoves().Length < 10 && !board.IsInCheck()) {
//             deepness ++;
//         }

//         (Move bestMove, double bestValue) = AlphaBeta(board, deepness, double.NegativeInfinity, double.PositiveInfinity, true, white);

//         return bestMove;
//     }

// // public (Move, double) Minimax(Board board, int depth, bool maximizingPlayer, int white)
// // {
// //     Move[] moves = board.GetLegalMoves();

// //     if (depth == 0 || moves.Length == 0)
// //     {
// //         return (new Move(), board.IsInCheckmate() 
// //             ? double.PositiveInfinity * (board.IsWhiteToMove ? -1 : 1)
// //             : board.IsDraw() ? 0 
// //             : nn.forward(board) * white);
// //     }

// //     Move bestMove = new Move();
// //     double value = maximizingPlayer ? double.NegativeInfinity : double.PositiveInfinity;

// //     foreach (Move move in moves)
// //     {
// //         board.MakeMove(move);
// //         (_, double childValue) = Minimax(board, depth - 1, !maximizingPlayer, white);
// //         board.UndoMove(move);

// //         if ((maximizingPlayer && childValue >= value) || (!maximizingPlayer && childValue <= value))
// //         {
// //             value = childValue;
// //             bestMove = move;
// //         }
// //     }

// //     return (bestMove, value);
// // }
// public (Move, double) AlphaBeta(Board board, int depth, double alpha, double beta, bool maximizingPlayer, int white, int step = 0)
// {
//     Move[] moves = board.GetLegalMoves();

//     if (depth == 0 || moves.Length == 0)
//     {
//         return (new Move(), board.IsInCheckmate() 
//             ? (1000 / step) * (board.IsWhiteToMove ? -1 : 1)
//             : board.IsDraw() ? 0 
//             : nn.forward(board) * white);
//     }

//     Move bestMove = new Move();
//     double value = maximizingPlayer ? double.NegativeInfinity : double.PositiveInfinity;

//     foreach (Move move in moves)
//     {
//         board.MakeMove(move);
//         (_, double childValue) = AlphaBeta(board, depth - 1, alpha, beta, !maximizingPlayer, white, step + 1);
//         board.UndoMove(move);

//         if ((maximizingPlayer && childValue >= value) || (!maximizingPlayer && childValue <= value))
//         {
//             value = childValue;
//             bestMove = move;
//         }

//         if (maximizingPlayer) alpha = Math.Max(alpha, value);
//         else beta = Math.Min(beta, value);

//         if (beta <= alpha) break;
//     }

//     return (bestMove, value);
// }

// // public (Move, double) Minimax(Board board, int depth, bool maximizingPlayer, int white)
// // {
// //     Move[] moves = board.GetLegalMoves();

// //     // If depth is 0 or node is a terminal node.
// //     if (depth == 0 || moves.Length == 0)
// //     {
// //         double value;
// //         if (board.IsInCheckmate())
// //         {
// //             int winner = board.IsWhiteToMove ? -1 : 1;
// //             value = double.PositiveInfinity * winner;;
// //         }
// //         else if (board.IsDraw())
// //         {
// //             value = 0;
// //         }
// //         else
// //         {
// //             value = nn.forward(board) * white;
// //         }
// //         return (new Move(), value);
// //     }

// //     Move bestMove = new Move();
// //     if (maximizingPlayer)
// //     {
// //         double value = double.NegativeInfinity;

// //         foreach (Move move in moves)
// //         {
// //             board.MakeMove(move);
// //             (_, double childValue) = Minimax(board, depth - 1, false, white);
// //             board.UndoMove(move);

// //             if (childValue > value)
// //             {
// //                 value = childValue;
// //                 bestMove = move;
// //             }
// //         }

// //         return (bestMove, value);
// //     }
// //     else // minimizing player
// //     {
// //         double value = double.PositiveInfinity;

// //         foreach (Move move in moves)
// //         {
// //             board.MakeMove(move);
// //             (_, double childValue) = Minimax(board, depth - 1, true, white);
// //             board.UndoMove(move);

// //             if (childValue < value)
// //             {
// //                 value = childValue;
// //                 bestMove = move;
// //             }
// //         }

// //         return (bestMove, value);
// //     }
// // }

//     public delegate void AssignValueAction(int index, double value);

//     public static void LoadParamsHelper(string[] variableNames, int length, int zeropoint, double scale, AssignValueAction assignValue)
//     {
//         int abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_;
//         char[] encodingArray = nameof(abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_).ToCharArray();

//         string concatenatedStr = "";
//         foreach (var variableName in variableNames)
//         {
//             var encodedStr = variableName.Substring(3);
//             concatenatedStr += encodedStr;
//         }

//         int i, idx = 0;
//         for (i = 0; i < length; i++)
//         {
//             string encodedVal = concatenatedStr.Substring(idx, 2);
//             int decoded = Array.IndexOf(encodingArray, encodedVal[0]) * 63 + Array.IndexOf(encodingArray, encodedVal[1]) - 128;
//             double dequantized = (decoded - zeropoint) /  scale;
//             assignValue(i, dequantized);
//             idx += 2;
//         }
//     }

//     public static double[][] LoadParams(string[] variableNames, int rows, int columns, int zeropoint, double scale)
//     {
//         double[][] result = new double[rows][];
//         for (int i = 0; i < rows; i++)
//             result[i] = new double[columns];
//         LoadParamsHelper(variableNames, rows * columns, zeropoint, scale, (idx, value) => result[idx / columns][idx % columns] = value);
//         return result;
//     }

//     public static double[] LoadParams(string[] variableNames, int length, int zeropoint, double scale)
//     {
//         double[] result = new double[length];
//         LoadParamsHelper(variableNames, length, zeropoint, scale, (idx, value) => result[idx] = value);
//         return result;
//     }


// }

// // public class NeuralNetwork
// // {
// //     private double[][][] fc_weights;
// //     private double[][] fc_biases, embedding;


// //     public NeuralNetwork(double[][][] fc_weights, double[][] fc_biases, double[][] embedding)
// //     {
// //         this.fc_weights = fc_weights;
// //         this.fc_biases = fc_biases;
// //         this.embedding = embedding;
// //     }
// //     public double[] FeedForward(double[] input)
// //     {
// //         int i, j, k;
// //         for (i = 0; i < fc_weights.Length; i++)
// //         {
// //             double[] layerOutput = new double[fc_weights[i].Length];
// //             for (j = 0; j < fc_weights[i].Length; j++)
// //             {
// //                 double sum = 0;
// //                 for (k = 0; k < fc_weights[i][j].Length; k++)
// //                     sum += input[k] * fc_weights[i][j][k];
// //                 // no relu on the last layer
// //                 layerOutput[j] = i != fc_weights.Length - 1 ? Math.Max(0, (sum + fc_biases[i][j])) : sum;
// //             }
// //             input = layerOutput;
// //         }
// //         return input;
// //     }
// //     public double forward(Board board)
// //     {
// //         double[] boardStateCopy, e;
// //         boardStateCopy = new double[261];
// //         for (int i = 0; i < 64; i++)
// //         {
// //             Piece piece = board.GetPiece(new Square(i));
// //             e = embedding[(piece == null) ? 0 : piece.IsWhite ? (int)piece.PieceType : (int)piece.PieceType + 6];
// //             // embedding size is 4
// //             for (int j = 0; j < 4; j++)
// //                 boardStateCopy[j * 64 + i] = e[j];
// //         }

// //         // 64 * 4;
// //         boardStateCopy[256] = board.IsWhiteToMove ? 1.0 : 0.0;
// //         boardStateCopy[257] = board.HasKingsideCastleRight(true) ? 1.0 : 0.0;
// //         boardStateCopy[258] = board.HasQueensideCastleRight(true) ? 1.0 : 0.0;
// //         boardStateCopy[259] = board.HasKingsideCastleRight(false) ? 1.0 : 0.0;
// //         boardStateCopy[260] = board.HasQueensideCastleRight(false) ? 1.0 : 0.0;

// //         // if turn is negative

// //         return FeedForward(boardStateCopy)[0];
// //     }
// // }

// public class NeuralNetwork
// {
//     private double[][][] fc_weights;
//     private double[][] fc_biases, embedding;

//     public NeuralNetwork(double[][][] fc_weights, double[][] fc_biases, double[][] embedding)
//     {
//         this.fc_weights = fc_weights;
//         this.fc_biases = fc_biases;
//         this.embedding = embedding;
//     }

//     public double[] FeedForward(double[] input)
//     {
//         int i, j;
//         for (i = 0; i < fc_weights.Length; i++)
//         {
//             double[] layerOutput = new double[fc_weights[i].Length];
//             for (j = 0; j < fc_weights[i].Length; j++)
//             {
//                 Vector<double> sum = Vector<double>.Zero;
//                 int k;
//                 for (k = 0; k <= fc_weights[i][j].Length - Vector<double>.Count; k += Vector<double>.Count)
//                 {
//                     var inputVector = new Vector<double>(input, k);
//                     var weightsVector = new Vector<double>(fc_weights[i][j], k);
//                     sum += inputVector * weightsVector;
//                 }
//                 double scalarSum = 0;
//                 for (; k < fc_weights[i][j].Length; k++)
//                 {
//                     scalarSum += input[k] * fc_weights[i][j][k];
//                 }

//                 double totalSum = Vector.Dot(sum, Vector<double>.One) + scalarSum;
//                 // no relu on the last layer
//                 layerOutput[j] = i != fc_weights.Length - 1 ? Math.Max(0, (totalSum + fc_biases[i][j])) : totalSum;
//             }
//             input = layerOutput;
//         }
//         return input;
//     }
//     //     public double forward(Board board)
//     // {
//     //     double[] boardStateCopy, e;
//     //     boardStateCopy = new double[261];
//     //     for (int i = 0; i < 64; i++)
//     //     {
//     //         Piece piece = board.GetPiece(new Square(i));
//     //         e = embedding[(piece == null) ? 0 : piece.IsWhite ? (int)piece.PieceType : (int)piece.PieceType + 6];
//     //         // embedding size is 4
//     //         for (int j = 0; j < 4; j++)
//     //             boardStateCopy[j * 64 + i] = e[j];
//     //     }

//     //     // 64 * 4;
//     //     boardStateCopy[256] = board.IsWhiteToMove ? 1.0 : 0.0;
//     //     boardStateCopy[257] = board.HasKingsideCastleRight(true) ? 1.0 : 0.0;
//     //     boardStateCopy[258] = board.HasQueensideCastleRight(true) ? 1.0 : 0.0;
//     //     boardStateCopy[259] = board.HasKingsideCastleRight(false) ? 1.0 : 0.0;
//     //     boardStateCopy[260] = board.HasQueensideCastleRight(false) ? 1.0 : 0.0;

//     //     // if turn is negative

//     //     return FeedForward(boardStateCopy)[0];
//     // }
//             public double forward(Board board)
//     {
//         double[] boardStateCopy, e;
//         boardStateCopy = new double[261];
//         for (int i = 0; i < 64; i++)
//         {
//             Piece piece = board.GetPiece(new Square(i));
//             e = embedding[(piece == null) ? 0 : piece.IsWhite ? (int)piece.PieceType : (int)piece.PieceType + 6];
//             // embedding size is 4
//             for (int j = 0; j < 4; j++)
//                 boardStateCopy[j * 64 + i] = e[j];
//         }

//         // 64 * 4;
//         boardStateCopy[256] = board.IsWhiteToMove ? 1.0 : 0.0;
//         boardStateCopy[257] = board.HasKingsideCastleRight(true) ? 1.0 : 0.0;
//         boardStateCopy[258] = board.HasQueensideCastleRight(true) ? 1.0 : 0.0;
//         boardStateCopy[259] = board.HasKingsideCastleRight(false) ? 1.0 : 0.0;
//         boardStateCopy[260] = board.HasQueensideCastleRight(false) ? 1.0 : 0.0;

//         // if turn is negative

//         return FeedForward(boardStateCopy)[0];
//     }
// }